<?php
/**
 * MagePrince
 * Copyright (C) 2020 Mageprince <info@mageprince.com>
 *
 * @package Mageprince_Productattach
 * @copyright Copyright (c) 2020 Mageprince (http://www.mageprince.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author MagePrince <info@mageprince.com>
 */
?>
<?php
/** @var \Mageprince\Productattach\Block\Attachment $block */
?>
<?php if ($block->isEnable()): ?>
    <?php $attachments = $block->getAllAttachment(); ?>
    <?php if ($attachments->getData()):?>
        <div class="all-attachment-block">
            <table class="table attachment-table">
                <thead>
                    <tr>
                        <?php if ($block->isEnableIcon()): ?>
                            <th><?= /* @noEscape */ __('Icon') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableLabel()): ?>
                            <th><?= /* @noEscape */ __('Label') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableDescription()): ?>
                            <th><?= /* @noEscape */ __('Description') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableFileType()): ?>
                            <th><?= /* @noEscape */ __('Type') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableAttachmentSize()): ?>
                            <th><?= /* @noEscape */ __('Size') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableDownload()): ?>
                            <th class="download"><?= /* @noEscape */ __('Download') ?></th>
                        <?php endif; ?>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($attachments as $attachment): ?>
                    <?php if ($attachment->getActive()): ?>
                        <?php $isSize = $block->isEnableAttachmentSize() ?>
                            <tr>
                                <?php if ($attachment->getFile() && $block->fileExists($attachment->getFile())): ?>
                                    <?php if ($block->isEnableIcon()): ?>
                                        <td class="attachment-icon">
                                            <img src="<?= $block->escapeUrl($block->getFileIcon($attachment->getFileExt())) ?>"
                                                 alt="<?= /* @noEscape */ $attachment->getFileExt() ?>"/>
                                        </td>
                                    <?php endif; ?>
                                    <?php if ($block->isEnableLabel()): ?>
                                        <td><?= /* @noEscape */ __($attachment->getName()); ?></td>
                                    <?php endif; ?>
                                    <?php if ($block->isEnableDescription()): ?>
                                        <td><?= /* @noEscape */ __($attachment->getDescription()); ?></td>
                                    <?php endif; ?>
                                    <?php if ($block->isEnableFileType()): ?>
                                        <td><?= /* @noEscape */ __($attachment->getFileExt()) ?></td>
                                    <?php endif; ?>
                                    <?php if ($isSize && $block->isEnableAttachmentSize()): ?>
                                        <td>
                                            <?= /* @noEscape */ __($block->getFileSize($attachment->getFile())); ?>
                                        </td>
                                    <?php endif; ?>
                                    <?php if ($block->isEnableDownload()): ?>
                                        <td class="download-attachment">
                                            <a href="<?= $block->escapeUrl($block->getAttachmentUrl($attachment->getFile())) ?>"
                                               target="_blank">
                                                <?= /* @noEscape */ __('Download') ?>
                                            </a>
                                        </td>
                                    <?php endif; ?>
                                <?php elseif ($attachment->getUrl()): ?>
                                    <?php if ($block->isEnableIcon()): ?>
                                        <td class="attachment-icon">
                                            <img src="<?= $block->escapeUrl($block->getLinkIcon()) ?>"
                                                 alt="<?= /* @noEscape */ $attachment->getFileExt() ?>"/>
                                        </td>
                                    <?php endif; ?>
                                    <?php if ($block->isEnableLabel()): ?>
                                        <td><?= /* @noEscape */ __($attachment->getName()); ?></td>
                                    <?php endif; ?>
                                    <?php if ($block->isEnableDescription()): ?>
                                        <td><?= /* @noEscape */ __($attachment->getDescription()); ?></td>
                                    <?php endif; ?>
                                    <?php if ($block->isEnableFileType()): ?>
                                        <td><?= /* @noEscape */ __('N/A') ?></td>
                                    <?php endif; ?>
                                    <?php if ($block->isEnableAttachmentSize()): ?>
                                        <td><?= /* @noEscape */ __('N/A') ?></td>
                                    <?php endif; ?>
                                    <?php if ($block->isEnableDownload()): ?>
                                        <td class="download-attachment">
                                            <a href="<?= $block->escapeUrl($attachment->getUrl()) ?>"
                                               target="_blank">
                                                <?= /* @noEscape */ __('Download') ?>
                                            </a>
                                        </td>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
<?php endif; ?>
