<?php
/**
 * MagePrince
 * Copyright (C) 2020 Mageprince <info@mageprince.com>
 *
 * @package Mageprince_Productattach
 * @copyright Copyright (c) 2020 Mageprince (http://www.mageprince.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author MagePrince <info@mageprince.com>
 */
?>
<?php
/** @var \Mageprince\Productattach\Block\Attachment $block */
?>
<?php if ($block->isEnable()): ?>
    <?php $productId = $block->getCurrentId(); ?>
    <?php $attachments = $block->getAttachment($productId); ?>
    <?php if ($attachments->getSize()):?>
        <?php if ($block->getAttachmentView() == 'list'): ?>
            <?php foreach ($attachments as $attachment): ?>
                <div class="product-attachment">
                    <?php if ($attachment->getFile() && $block->fileExists($attachment->getFile())): ?>
                        <a href="<?= /* @noEscape */  $block->getAttachmentUrl($attachment->getFile()); ?>" target="_blank">
                            <?php if ($block->isEnableListViewIcon()): ?>
                                <div class="attachment-icon">
                                    <img src="<?= $block->escapeUrl($block->getFileIcon($attachment->getFileExt())) ?>"
                                         alt="<?= /* @noEscape */ $attachment->getFileExt() ?>"/>
                                </div>
                            <?php endif; ?>
                            <?php if ($block->isEnableListViewLabel()): ?>
                                <?= /* @noEscape */  $attachment->getName(); ?>
                            <?php endif; ?>
                        </a>
                        <?php if ($block->isEnableListViewSize()): ?>
                            <?php $size = '('.__('Size:').$block->getFileSize($attachment->getFile()).')' ?>
                            <?= /* @noEscape */ __($size); ?>
                        <?php endif; ?>
                    <?php elseif ($attachment->getUrl()): ?>
                        <a href="<?= /* @noEscape */  $attachment->getUrl(); ?>" target="_blank" >
                            <?php if ($block->isEnableListViewIcon()): ?>
                                <div class="attachment-icon">
                                    <img src="<?= $block->escapeUrl($block->getLinkIcon()) ?>"
                                         alt="<?= /* @noEscape */ $attachment->getFileExt() ?>"/>
                                </div>
                            <?php endif; ?>
                            <?php if ($block->isEnableListViewLabel()): ?>
                                <?= /* @noEscape */ __($attachment->getName()); ?>
                            <?php endif; ?>
                        </a>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <table class="table attachment-table">
                <?php if ($block->isEnableTableViewHeader()): ?>
                <thead>
                    <tr>
                        <?php if ($block->isEnableTableViewIcon()): ?>
                            <th><?= /* @noEscape */ __('Icon') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableTableViewLabel()): ?>
                            <th><?= /* @noEscape */ __('Label') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableTableViewDescription()): ?>
                            <th><?= /* @noEscape */ __('Description') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableTableViewType()): ?>
                            <th><?= /* @noEscape */ __('Type') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableTableViewSize()): ?>
                            <th><?= /* @noEscape */ __('Size') ?></th>
                        <?php endif; ?>
                        <?php if ($block->isEnableTableViewDownload()): ?>
                            <th class="download"><?= /* @noEscape */ __('Download') ?></th>
                        <?php endif; ?>
                    </tr>
                </thead>
                <?php endif; ?>
                <tbody>
                <?php foreach ($attachments as $attachment): ?>
                    <tr>
                        <?php if ($attachment->getFile() && $block->fileExists($attachment->getFile())): ?>
                            <?php if ($block->isEnableTableViewIcon()): ?>
                                <td class="attachment-icon">
                                    <img src="<?= $block->escapeUrl($block->getFileIcon($attachment->getFileExt())) ?>"
                                         alt="<?= /* @noEscape */ $attachment->getFileExt() ?>"/>
                                </td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewLabel()): ?>
                                <td><?= /* @noEscape */ __($attachment->getName()); ?></td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewDescription()): ?>
                                <td><?= /* @noEscape */ __($attachment->getDescription()); ?></td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewType()): ?>
                                <td><?= /* @noEscape */ __($attachment->getFileExt()) ?></td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewSize()): ?>
                                <td>
                                    <?= /* @noEscape */ __($block->getFileSize($attachment->getFile())); ?>
                                </td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewDownload()): ?>
                                <td class="download-attachment">
                                    <a href="<?= $block->escapeUrl($block->getAttachmentUrl($attachment->getFile())) ?>"
                                       target="_blank">
                                        <?= /* @noEscape */ __('Download') ?>
                                    </a>
                                </td>
                            <?php endif; ?>
                        <?php elseif ($attachment->getUrl()): ?>
                            <?php if ($block->isEnableTableViewIcon()): ?>
                                <td class="attachment-icon">
                                    <img src="<?= $block->escapeUrl($block->getLinkIcon()) ?>"
                                         alt="<?= /* @noEscape */ $attachment->getFileExt() ?>"/>
                                </td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewLabel()): ?>
                                <td><?= /* @noEscape */ __($attachment->getName()); ?></td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewDescription()): ?>
                                <td><?= /* @noEscape */ __($attachment->getDescription()); ?></td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewType()): ?>
                                <td><?= /* @noEscape */ __('N/A') ?></td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewSize()): ?>
                                <td><?= /* @noEscape */ __('N/A') ?></td>
                            <?php endif; ?>
                            <?php if ($block->isEnableTableViewDownload()): ?>
                                <td class="download-attachment">
                                    <a href="<?= $block->escapeUrl($attachment->getUrl()) ?>"
                                       target="_blank" >
                                        <?= /* @noEscape */ __('Download') ?>
                                    </a>
                                </td>
                            <?php endif; ?>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
