<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shipping Rules for Magento 2
 */ /** @var \Amasty\Shiprules\Block\Adminhtml\System\Config\CommonRulesNotification $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php if ($block->shouldShowNotification()): ?>
    <div>
        <p class="message message-notice">
            <?= $escaper->escapeHtml($block->getNotificationText()) ?>
        </p>
    </div>
<?php endif;?>
