<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Block\System\Config\Field;

use Magento\Framework\View\Element\Context;
use Magento\Framework\View\Element\Html\Select;
use Magento\Tax\Model\System\Config\Source\Tax\Display\Type;

class PriceDisplayType extends Select
{
    /**
     * @var Type
     */
    public $priceDisplayTypes;

    /**
     * PriceDisplayType constructor.
     *
     * @param Context                  $context
     * @param Type                     $priceDisplayTypes
     * @param array                    $data
     */
    public function __construct(
        Context $context,
        Type $priceDisplayTypes,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->priceDisplayTypes = $priceDisplayTypes;
    }

    /**
     * Sets name
     *
     * @param string $value
     *
     * @return $this
     */
    public function setInputName(string $value): PriceDisplayType
    {
        $this->setData('name', $value);
        return $this;
    }

    /**
     * Render block HTML
     *
     * @return string
     */
    public function _toHtml(): string
    {
        if (!$this->getOptions()) {
            $options = $this->priceDisplayTypes->toOptionArray();
            foreach ($options as $option) {
                $this->addOption($option['value'], $option['label']);
            }
        }
        return parent::_toHtml();
    }
}
