<?php
/**
 * @var \Bss\CustomTheme\Block\MegaMenu $block
 */
?>
<?php
$childsLv1Cat = $block->getLevel1ChildCategories();
$topProducts = $block->getTopProducts();
?>
<div class="">
    <?php if (!empty($childsLv1Cat)): ?>
    <?php foreach ($childsLv1Cat as $childsLv1CatItem): ?>
    <div class="ph-type-4 ph-col ph-col-3">
        <div class="col-md-12">
            <h3 class="ph-mega-categories-cat-title cat_<?= $childsLv1CatItem->getId(); ?>">
                <a href="<?= $childsLv1CatItem->getUrl() ?>" title="<?= $childsLv1CatItem->getName() ?>"><?= $childsLv1CatItem->getName() ?></a>
            </h3>
            <ul class="ph-mega-categories-list-lvl-1">
                <?php $childsLv2 = $childsLv1CatItem->getChildrenCategories(); ?>
                <?php if (!empty($childsLv2)) : ?>
                    <?php foreach ($childsLv2 as $item) : ?>
                        <li class="cat_<?= $item->getId(); ?> ">
                            <a href="<?= $item->getUrl() ?>" title="<?= $item->getName() ?>"><?= $item->getName() ?></a>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </div>
    </div>
    <?php endforeach; ?>
    <?php endif; ?>
    <div class="ph-type-6 ph-col ph-col-3">
        <div class="col-sm-12">
            <h3><?= $block->escapeHtml(__('Top 5 producten')) ?></h3>
            <ol class="product_list_ph">
                <?php if (!empty($topProducts)) : ?>
                    <?php foreach ($topProducts as $product) : ?>
                        <li class="ph_product_item">
                            <a href="<?= $product->getProductUrl(); ?>" title="<?= $product->getName(); ?>"> <?= $product->getName(); ?> </a>
                            <a class="ajax_add_to_cart_button btn btn-primary btn-round" href="https://www.glasgigant.nl/winkelmandje?add=1&amp;id_product=625&amp;token=e54f267d26f56bb53cb84b28c80c7ed0" rel="nofollow" title="Add to cart" data-id-product="<?= $product->getId(); ?>">
                                <i class="icon-shopping-cart"></i>
                            </a>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ol>
        </div>
    </div>
    <div class="ph-type-5 ph-col ph-col-12 ph-new-row">
        <h3></h3>
        <div class="alert alert-warning alert-menu">
            <div class="alert-menu-image">
                <img src="https://glasgigant.nl/img/cms/mechanic.png" alt="" width="113" height="109" class="pull-left">
            </div>
            <a href="/79-keuzehulp" class="btn btn-secondary pull-right">Open de glaskeuzehulp <em class="icon-chevron-right"></em>
            </a>
            <p>Hulp nodig bij het kiezen? Gebruik onze glaskeuzehulp!</p>
            <div class="clearfix"></div>
        </div>
    </div>
</div>