<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_DependentCustomOption
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
use Magento\Catalog\Model\Product\Option;

/**
 * Date options block
 *
 * @var \Bss\DependentCustomOption\Block\Options\Type\Date $block
 */
?>
<?php $option = $block->getOption() ?>
<?php $optionId = $option->getId() ?>
<?php $class = ($option->getIsRequire()) ? ' required' : ''; ?>
<div class="field date <?php echo $class; ?>"
    id="bss_options_<?php echo $option->getId() ?>"
    data-mage-init='{"priceOptionDate":{"fromSelector":"#product_addtocart_form"}}'>
    <fieldset class="fieldset fieldset-product-options-inner<?php echo $class; ?>">
        <legend class="legend">
            <span><?php echo  $block->escapeHtml($option->getTitle()) ?></span>
            <?php echo $block->getFormatedPrice() ?>
            <?php  echo $block->getBssCustomOptionBlock('after_title'); ?>
        </legend>
        <?php echo $block->getBssCustomOptionBlock('before_control'); ?>
        <div class="control">
            <?php if ($option->getType() == Option::OPTION_TYPE_DATE_TIME
                || $option->getType() == Option::OPTION_TYPE_DATE): ?>

                <?php echo $block->getDateHtml() ?>

            <?php endif; ?>

            <?php if ($option->getType() == Option::OPTION_TYPE_DATE_TIME
                || $option->getType() == Option::OPTION_TYPE_TIME): ?>
                <?php echo $block->getTimeHtml() ?>
            <?php endif; ?>

            <?php if ($option->getIsRequire()): ?>
                <input type="hidden"
                       name="validate_datetime_<?php echo $optionId ?>"
                       class="validate-datetime-<?php echo $optionId ?>"
                       value=""
                       data-validate="{'validate-required-datetime':<?php echo $optionId?>}"/>
            <?php else: ?>
                <input type="hidden"
                       name="validate_datetime_<?php echo $optionId ?>"
                       class="validate-datetime-<?php echo $optionId ?>"
                       value=""
                       data-validate="{'validate-optional-datetime':<?php echo $optionId?>}"/>
            <?php endif; ?>
            <script type="text/x-magento-init">
            {
                "#product_addtocart_form": {
                    "validation": {
                        "ignore": ":hidden"
                    }
                }
            }
        </script>
        </div>
    </fieldset>
    <?php  echo $block->getBssCustomOptionBlock('after_control'); ?>
</div>
