<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_DependentCustomOption
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * File options block
 *
 * @var \Bss\DependentCustomOption\Block\Options\Type\File $block
 */
?>
<?php $option = $block->getOption(); ?>
<?php $fileInfo = $block->getFileInfo(); ?>
<?php $fileExists = $fileInfo->hasData(); ?>
<?php $fileName = 'options_' . $option->getId() . '_file'; ?>
<?php $fieldNameAction = $fileName . '_action'; ?>
<?php $fieldValueAction = $fileExists ? 'save_old' : 'save_new'; ?>
<?php $fileNamed = $fileName . '_name'; ?>
<?php $class = ($option->getIsRequire()) ? ' required' : ''; ?>

<div class="field file<?php echo $class; ?>" id="bss_options_<?php echo $option->getId() ?>">
    <label class="label" for="<?php echo $fileName; ?>" id="<?php echo $fileName; ?>-label">
        <span><?php echo  $block->escapeHtml($option->getTitle()) ?></span>
        <?php echo $block->getFormatedPrice() ?>
        <?php  echo $block->getBssCustomOptionBlock('after_title'); ?>
    </label>
    <?php echo $block->getBssCustomOptionBlock('before_control'); ?>
    <?php if ($fileExists): ?>
    <div class="control">
        <span class="<?php echo $fileNamed ?>"><?php echo $block->escapeHtml($fileInfo->getTitle()); ?></span>
        <a href="javascript:void(0)" class="label" id="change-<?php echo $fileName ?>" >
            <?php echo __('Change') ?>
        </a>
        <?php if (!$option->getIsRequire()): ?>
            <input type="checkbox" id="delete-<?php echo $fileName ?>" />
            <span class="label"><?php echo __('Delete') ?></span>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <div class="control" id="input-box-<?php echo $fileName ?>"
             data-mage-init='{"priceOptionFile":{
                "fileName":"<?php echo $fileName ?>",
                "fileNamed":"<?php echo $fileNamed ?>",
                "fieldNameAction":"<?php echo $fieldNameAction ?>",
                "changeFileSelector":"#change-<?php echo $fileName ?>",
                "deleteFileSelector":"#delete-<?php echo $fileName ?>"}
             }'
            <?php echo $fileExists ? 'style="display:none"' : '' ?>>
        <input type="file"
               name="<?php echo $fileName; ?>"
               id="<?php echo $fileName; ?>"
               class="product-custom-option<?php echo $option->getIsRequire() ? ' required' : '' ?>"
               <?php echo $fileExists ? 'disabled="disabled"' : '' ?> />
        <input type="hidden" name="<?php echo $fieldNameAction; ?>" value="<?php echo $fieldValueAction; ?>" />
        <?php if ($option->getFileExtension()): ?>
            <p class="note">
                <?php echo __('Compatible file extensions to upload')?>: <strong><?php echo $option->getFileExtension() ?></strong>
            </p>
        <?php endif; ?>
        <?php if ($option->getImageSizeX() > 0): ?>
            <p class="note">
                <?php echo __('Maximum image width')?>: <strong><?php echo $option->getImageSizeX() ?> <?php echo __('px.')?></strong>
            </p>
        <?php endif; ?>
        <?php if ($option->getImageSizeY() > 0): ?>
            <p class="note">
                <?php echo __('Maximum image height')?>: <strong><?php echo $option->getImageSizeY() ?> <?php echo __('px.')?></strong>
            </p>
        <?php endif; ?>
    </div>
    <?php  echo $block->getBssCustomOptionBlock('after_control'); ?>
</div>
