<?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block') ->setBlockId('boven-de-header') ->toHtml(); ?>
<div class="header-container header-style-1">
	<div class="header-top">
		<div class="container">
			<div class="row row-topheader">
				<div class="col-lg-5 col-md-5 language-currency-top">
					<?php echo $block->getChildHtml('language-header'); ?>
					<?php echo $block->getChildHtml('currency-header'); ?>
				</div>
				
				<div class="col-lg-7 col-md-7 header-top-links">
					<div class="toplinks-wrapper">
					<div class="menu-top">
<?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block') ->setBlockId('links-header') ->toHtml(); ?>
</div>
</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="header-middle">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 logo-header">
					<?php echo $block->getChildHtml('logo_theme'); ?>
				</div>
				
				<div class="col-lg-8 header-middle-right">
					<div class="middle-right-content">
						<div class="searchbox-header">
							<?php echo $block->getChildHtml('search-header-pro'); ?>
						</div>
						<div class="accountinfo">
						<a href="/customer/account/login"><i class="fas fa-user"></i></a>
						<div class="inloggen"><?php						
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

if ($customerSession->isLoggedIn()) {
    $customerSession->getCustomerId();  // get Customer Id
    $customerSession->getCustomerGroupId();
    $customerSession->getCustomer();
    $customerSession->getCustomerData();
    echo __('<span>Welkom</span>');
}
else { echo __('Hallo.<a href="/customer/account/login"> Inloggen</a>');
}
	 ?>
						
					
						
						</div>
						<div class="customer-action">
						
						<div class="myaccount">Mijn account</div>
						 <div class="dropdown-user">
						 <div class="user-chevron"></div>
						 <div class="user-items">
						 <?php echo $block->getChildHtml('toplinks-header'); ?>
						 <span>Account bekijken</span>
						 <li><a href="/customer/account/create">Een account registreren</a></li>
						 <span>Sneller bestellen</span>
									</div>
                                </div>
						</div>
						</div>
						<div class="minicart-header">
								<?php echo $block->getChildHtml('cart-header'); ?>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="header-bottom">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 sidebar-megamenu">
					<div class="megamenu-content-sidebar">
						<div class="btn-megamenu">
							<a href="javascript:void(0)" title="<?php echo __('All Categories') ?>"><?php echo __('All Categories') ?></a>
						</div>
						
						<div class="menu-ver-content">
							<?php
							if ($_config->getGeneral('menu_style') == 'megamenu') {
								echo $block->getChildHtml('navigation-header-megamenu');
							} else {
								echo $block->getChildHtml('navigation-header');
							}
							?>
						</div>
					</div>
					
					<div class="navigation-mobile-container">
					    <div class="nav-mobile-container sidebar-type">
		<div class="btn-mobile">
			<a id="sidebar-button" class="button-mobile sidebar-nav" title="<?php echo __('Categories') ?>"><i class="fa fa-bars"></i><span class="hidden"><?php echo __('Categories') ?></span></a>
		</div>

		<?php if ($menuType == 'megamenu') { ?>
            <nav id="navigation-mobile" class="navigation-mobile"></nav>
            <script type="text/javascript">
                require([
                    'jquery'
                ], function ($) {
                    $('#sidebar-button').click(function () {
                        $('body').toggleClass('navbar-active');
                        $(this).toggleClass('active');
                    });
                });
            </script>
        <?php } else { ?>
            
            <nav class="navigation-mobile">
<div class="login-create">
<ul>
<li><a href="/customer/account/create">Account aanmaken</a></li>
<li><a href="/customer/account/login">Inloggen</a></li>
</ul>
</div>
<div class="menulinks">
<ul><?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block') ->setBlockId('mobile-links') ->toHtml(); ?></ul>
</div>
<?php
$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menu        = $block->getHtml('level-top', 'submenu', $columnsLimit);
$_config      = $this->helper('Sm\Market\Helper\Data');
$menuType     = $_config->getGeneral('menu_style');
?>
               <?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block') ->setBlockId('mobile-menu-bouwtools') ->toHtml(); ?>

            </nav>

            <script type="text/javascript">
                require([
                    'jquery'
                ], function ($) {
                    $('#sidebar-button').click(function () {
                        $('body').toggleClass('navbar-active');
                        $(this).toggleClass('active');
                    });
                });
            </script>
			</div>
			<script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            $('.navigation-mobile > ul li').has('ul').append('<span class="touch-button"><span>open</span></span>');

            $('.touch-button').click(function () {
                $(this).prev().slideToggle(200);
                $(this).toggleClass('active');
                $(this).parent().toggleClass('parent-active');
            });
        });
    </script>
		<?php } ?>

	
					</div>
				</div>
				
				<div class="col-lg-9 col-md-9 main-megamenu">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	require([
        'jquery'
    ], function ($) {
        $(".header-style-1 .header-top .header-top-links .toplinks-wrapper .header.links li").not(".myaccount-link").mouseover(function () {
            $(".header-style-1 .header-top .header-top-links .toplinks-wrapper .header.links").addClass('toplinks_hover');
        }).mouseout(function () {
            $(".header-style-1 .header-top .header-top-links .toplinks-wrapper .header.links").removeClass('toplinks_hover');
        });
    });
</script>

