<?php if ($this->placement == 'external') : ?>
<h3>Your Mopinion tag</h3>
<p style="font-size:13px">
    If you chose to implement Mopinion with an external Tag Management solution, copy the following code and paste on your website after the closing <code><strong>body</strong></code> tag, or add it to your Tag Manager.        </p>

<textarea id="pasteaseContent" class="mopinion-code-block" readonly="true">&lt;!-- Mopinion Pastea.se start --&gt;
&lt;script type="text/javascript"&gt;(function(){var id="<?php echo $this->mopinionKey; ?>";var js=document.createElement("script");js.setAttribute("type","text/javascript");js.setAttribute("src","//deploy.mopinion.com/js/pastease.js");js.async=true;document.getElementsByTagName("head")[0].appendChild(js);var t=setInterval(function(){try{new Pastease.load(id);clearInterval(t)}catch(e){}},50)})();&lt;/script&gt;
&lt;!-- Mopinion Pastea.se end --&gt;</textarea>
<?php endif; ?>

<br>

<div style="background-color: #FFF;padding:1px 12px; border-left:4px solid #00a0d2; margin:25px 0; ">
  <p>If you want to change the questions, triggers or design of your feedback survey, please visit
    <a href="https://app.mopinion.com/survey/manage" target="_blank">app.mopinion.com</a>
  <br>
  Your Mopinion account is owned by user: <i><?php echo $this->email; ?></i>.
  </p>
</div>

<h3>Support</h3>
<p>Having issues with your install?      Don't hesitate to contact <a href="mailto:support@mopinion.com">support@mopinion.com</a></p>

<style>
/**
 * All of the CSS for your admin-specific functionality should be
 * included in this file.
 */

.mopinion-code-block
{
  width:100%;
  height:120px;
  font-size:13px;
  font-family: monospace;
}

.mopinion-option-note,
.mopinion-note
{
  font-size:12px;
  padding-top:5px;
  /*padding-left:25px;*/
  display:inline-block;
  font-style: italic;
}

</style>
