<p>
<strong>First, Let's set you up with a Mopinion account. (Totally <strong>free</strong> of course...)</strong>
</p>

<p>
The username for your Mopinion-account will be the email address you are currently logged in with.    <i>(<?php echo $this->email; ?>) </i>
<br>
After registration, you can login at    <a href="https://app.mopinion.com" target="_blank">https://app.mopinion.com</a>
<br>
<br>
All we need from you now is  your country and a password for your new account.
</p>