<br />

<?php /* common footer */ ?>
<div style="background-color: #FFF;padding:1px 12px; border-left:4px solid #00a0d2; margin:5px 0; ">
    <p>If you want to change the questions, triggers or design of your feedback survey, please visit <a href="https://app.mopinion.com/survey/manage" target="_blank">app.mopinion.com</a>                </p>
</div>

<h2>Support</h2>
<p>Having issues with your install? Don't hesitate to contact <a href="mailto:support@mopinion.com">support@mopinion.com</a></p>
