<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */

$_config   = $this->helper('Sm\Market\Helper\Data');
$homeStyle = $_config->getThemeLayout('home_style');

?>

<?php
switch ($type = $block->getType()) {

	case 'related-rule':
		if ($exist = $block->hasItems()) {
			$type  = 'related';
			$class = $type;

			$image             = 'related_products_list';
			$hover_image       = 'category_page_grid-hover';
			$title             = __('Related Products');
			$items             = $block->getAllItems();
			$limit             = $_config->getProductDetail('related_limit');
			$shuffle           = (int)$block->isShuffled();
			$canItemsAddToCart = $block->canItemsAddToCart();

			$showAddTo    = true;
			$showCart     = false;
			$templateType = null;
			$description  = false;
		}
		break;

	case 'related':
		/** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
		if ($exist = $block->getItems()->getSize()) {
			$type  = 'related';
			$class = $type;

			$image             = 'related_products_list';
			$hover_image       = 'category_page_grid-hover';
			$title             = __('Related Products');
			$items             = $block->getItems();
			$limit             = $_config->getProductDetail('related_limit');
			$shuffle           = 0;
			$canItemsAddToCart = $block->canItemsAddToCart();

			$showAddTo    = true;
			$showCart     = false;
			$templateType = null;
			$description  = false;
		}
		break;

	case 'upsell-rule':
		if ($exist = $block->hasItems()) {
			$type  = 'upsell';
			$class = $type;

			$image       = 'upsell_products_list';
			$hover_image = 'category_page_grid-hover';
			$title       = __('Dit heeft u misschien nodig');
			$items       = $block->getAllItems();
			$limit       = $_config->getProductDetail('upsell_limit');
			$shuffle     = (int)$block->isShuffled();

			$showAddTo         = false;
			$showCart          = false;
			$templateType      = null;
			$description       = false;
			$canItemsAddToCart = false;
		}
		break;

	case 'upsell':
		/** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
		if ($exist = count($block->getItemCollection()->getItems())) {
			$type  = 'upsell';
			$class = $type;

			$image       = 'upsell_products_list';
			$hover_image = 'category_page_grid-hover';
			$title       = __('Dit heeft u misschien nodig');
			$items       = $block->getItemCollection()->getItems();
			$limit       = $_config->getProductDetail('upsell_limit');
			$shuffle     = 0;

			$showAddTo         = false;
			$showCart          = false;
			$templateType      = null;
			$description       = false;
			$canItemsAddToCart = false;
		}
		break;
}
?>

<?php if ($exist): ?>


    <div class="related-upsell-wrapper block block-detail <?php /* @escapeNotVerified */
	echo $class; ?>">
    <div class="detail-title">
        <span id="block-<?php /* @escapeNotVerified */
		echo $class ?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */
			echo $title; ?></span>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */
	echo $class ?>-heading">
        <div class="grid products-grid products-<?php /* @escapeNotVerified */
		echo $type; ?>">
            <div class="grid-product-type products list items product-items slider-products" style="padding:0 40px;">
                <?php $i = 0;
				foreach ($items as $_item): $i++; ?>
                    <div class="item product product-item">
					<div class="item-inner">
						<div class="product-item-info">
							<div class="box-image">
								<a href="<?php /* @escapeNotVerified */
								echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
									<?php echo $block->getImage($_item, $image)->toHtml(); ?>
								</a>

                                <!--LABEL PRODUCT-->
								<?php
								$orgprice             = $_item->getPrice();
								$specialprice         = $_item->getSpecialPrice();
								$specialPriceFromDate = $_item->getSpecialFromDate();
								$specialPriceToDate   = $_item->getSpecialToDate();

								$today = new DateTime();

								if ($specialprice && $_config->getAdvanced('show_salelabel')) {
									$fromDate = new DateTime($specialPriceFromDate);
									$toDate = $specialPriceToDate ? new DateTime($specialPriceToDate) : null;

									if (($today >= $fromDate && $today <= $toDate) || ($today >= $fromDate && is_null($toDate))) {
										if ($specialprice < $orgprice) {
											$save_percent = 100 - round(($specialprice / $orgprice) * 100);
											?>
											<div class="label-product label-sale">
												<span class="sale-product-icon">
													<?php echo '-' . $save_percent . '%'; ?>
												</span>
											</div>
										<?php }
									}
								}
								?>

                                <!--END LABEL PRODUCT-->

								<?php if ($homeStyle == 'home-16' || $homeStyle == 'home-17' || $homeStyle == 'home-18' || $homeStyle == 'home-19' || $homeStyle == 'home-20') { ?>
                                    <div class="button-action">
										<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#" data-post='<?php /* @escapeNotVerified */
												echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */
												echo __('Add to Wish List') ?>">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Wish List') ?></span>
												</a>
											<?php endif; ?>
										<?php } ?>

										<?php if ($_config->getAdvanced('show_compare_button')) { ?>
											<?php if ($block->getAddToCompareUrl()): ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare btn-action link-compare" data-post='<?php /* @escapeNotVerified */
												echo $compareHelper->getPostDataParams($_item); ?>' data-role="add-to-links" title="<?php /* @escapeNotVerified */
												echo __('Add to Compare'); ?>">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Compare') ?></span>
												</a>
											<?php endif; ?>
										<?php } ?>
									</div>
								<?php } ?>
							</div>
							
							<?php
$productName = $block->escapeHtml($_item->getName());
$len = strlen($productName);
?>

							<div class="product details product-item-details box-info">
								<div class="product name product-item-name product-name">

									
									<a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
    <?php echo substr($productName,0,50); ?>
    <?php if($len > 55) echo '...'; ?>
</a>
									
									
									
								</div>

								<?php /* @escapeNotVerified */
								echo $block->getProductPrice($_item); ?>

								

								

										<div class="bekijken">
									<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"><span>Bekijken</span></a>
									</div>

									
							</div>
							
							
						</div>
					</div>
                </div>
					<?php if ($i == $limit) break; ?>
				<?php endforeach ?>
            </div>
        </div>
    </div>
</div>

 <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Catalog/js/slider-products": {
                "type": "<?= /* @escapeNotVerified */ $type ?>"
            }
        }
    }
    </script>
</script>
<?php endif; ?>
