<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @noinspection PhpUnhandledExceptionInspection */
/**
 * Top menu for store
 *
 * @var $block \Magedelight\Megamenu\Block\Topmenu
 */
$burgerStatus = $block->getConfigBurgerStatus();
$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getBurgerHtml('level-top', 'submenu', $columnsLimit);
?>

<nav class="navigation md-megamenu-burger" id="md-megamenu-burger" data-action="navigation" style="display: none;">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <span class="md-menu-close-btn"><?php echo __('Close Btn'); ?></span>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>
<script type="text/x-magento-init">
{
    "*": {
        "Magedelight_Megamenu/js/megamenu/burger" : {
            "burger_status": "<?= /* @noEscape */ $burgerStatus; ?>"
        }
    }
}
</script>