<?php
/**
 * MageDelight
 * Copyright (C) 2023 Magedelight <info@magedelight.com>
 *
 * @category MageDelight
 * @package Magedelight_Megamenu
 * @copyright Copyright (c) 2023 Magedelight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
/**
 * @var $block \Magedelight\Megamenu\Block\Topmenu
 * @var $viewModel \Magedelight\Megamenu\ViewModel\Topmenu
 */

$viewModel = $block->getData('viewModel');

$enableCustomMenu = $viewModel->enableCacheMenu();
$menuData = $viewModel->getMenuData();
?>
<?php if ($enableCustomMenu == 1 && $menuData != ''): ?>
    <?= $menuData; ?>
<?php else: ?>
    <?php ob_start();
    $columnsLimit = $block->getColumnsLimit() ? : 0;
    $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
    $isAmazonMenuCreated = $block->isAmazonMenuCreated();
    $_amazonMenu = $block->getAmazonMenuHtml();
    $mainClass = $block->getMenuClass();
    $burgerStatus = $block->getConfigBurgerStatus();
    $amazonClass = $isAmazonMenuCreated ? "horizontal has-amazon" : "";
    ?>
    <?php if ($block->isPrimaryMenuSelected() || $isAmazonMenuCreated): ?>
    <div class="menu-container horizontal-menu">
        <div data-action="navigation" class="<?= /* @noEscape */ $mainClass; ?> <?= $amazonClass?>">
            <?php if ($isAmazonMenuCreated) { ?>
                <div class="amazon-menu-btn">
                    <a href="javascript: void(0)"><?= __("Open Menu"); ?></a>
                    <!-- <span data-action="toggle-nav" class="action nav-toggle"><span>Toggle Nav</span></span> -->
                </div>
            <?php } ?>
            <?php if ($block->isPrimaryMenuSelected()): ?>
                <ul class="md-top-menu-items">
                    <?= /* @noEscape */ $_menu; ?>
                </ul>
                <?= /* @noEscape */ $block->menuStyleHtml(); ?>
            <?php endif; ?>
        </div>
        <?php if ($isAmazonMenuCreated) { ?>
            <div class="md-amazon-menu">
                <span class="md-menu-close-btn"></span>
                <div class="md-amazon-menu-content">
                    <?= /* @noEscape */ $_amazonMenu; ?>
                </div>
            </div>
        <?php } ?>
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magedelight_Megamenu/js/megamenu/topmenu" : {
                "animation_time": "<?= /* @noEscape */ $block->animationTime(); ?>",
                "display_overlay": "<?= /* @noEscape */ $block->getPrimaryMenuDisplayOverlay(); ?>"
            }
        }
    }
    </script>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magedelight_Megamenu/js/megamenu/amazonmenu" : {
                "animation_time": "<?= /* @noEscape */ $block->animationTime(); ?>",
                "display_overlay": "<?= /* @noEscape */ $block->getPrimaryMenuDisplayOverlay(); ?>"
            }
        }
    }
    </script>
<?php endif; ?>
    <?php if ($burgerStatus): ?>
        <?php
        $columnsLimit = $block->getColumnsLimit() ?: 0;
        $_menuHtml = $block->getBurgerHtml('level-top', 'submenu', $columnsLimit);
        ?>
    <nav class="navigation md-megamenu-burger" id="md-megamenu-burger" data-action="navigation" style="display: none;">
        <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <span class="md-menu-close-btn"><?= __('Close Btn'); ?></span>
            <?= /* @noEscape */ $_menuHtml?>
            <?= $block->getChildHtml() ?>
        </ul>
    </nav>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magedelight_Megamenu/js/megamenu/burger" : {
                    "burger_status": "<?= /* @noEscape */ $burgerStatus; ?>",
                    "display_overlay": "<?= /* @noEscape */ $block->getPrimaryMenuDisplayOverlay(); ?>"
                }
            }
        }
    </script>
    <?php endif; ?>
    <?php
    $storeMenuKey = $viewModel->getStoreMenuKey();
    $fileContent = ob_get_contents();
    $viewModel->saveVariableByCode($storeMenuKey, $fileContent);
    ob_end_flush();
    ?>
<?php endif; ?>
