<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div class="bottom-container">
    <div id="bottom" class="container">
        <div class="row">
            <div id="block_top_menu" class="clearfix col-xl-11 col-xs-12">
                <ul class="">
                    <li>
                        <a href="https://www.glasgigant.nl/content/privacy-cookies.html" title="Privacy- en cookies">
                            <?= $block->escapeHtml(__('Privacy- en cookies')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.glasgigant.nl/content/disclaimer.html" title="Disclaimer">
                            <?= $block->escapeHtml(__('Disclaimer')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.glasgigant.nl/content/algemene-voorwaarden.html" title="Algemene voorwaarden">
                            <?= $block->escapeHtml(__('Algemene voorwaarden')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.glasgigant.nl/content/garantiebepalingen.html" title="Garantiebepalingen">
                            <?= $block->escapeHtml(__('Garantiebepalingen')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.glasgigant.nl/content/bokkenreglement.html" title="Bokkenreglement">
                            <?= $block->escapeHtml(__('Bokkenreglement')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="/sitemap" title="Sitemap">
                            <?= $block->escapeHtml(__('Sitemap')) ?>
                        </a>
                    </li>
                </ul>
            </div>
            <section id="social_block" class="col-xl-1 col-xs-12">
                <ul>
                    <li class="facebook">
                        <a class="_blank" href="https://www.facebook.com/GlasGigant/" target="_blank">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </li>
                    <li class="youtube">
                        <a class="_blank" href="https://www.youtube.com/channel/UCIt-E2Lz7iMX1Tt-iDDtI9A" target="_blank">
                            <i class="fa fa-youtube-play"></i>
                        </a>
                    </li>
                </ul>
            </section>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
