<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div id="cmsinfo_block">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-sm-6 nonrelative">
                <h2><?= $block->escapeHtml(__('Bestellen bij Glas')); ?><span class="orange"><?= $block->escapeHtml(__('Gigant')); ?></span><?= $block->escapeHtml(__('.nl is heel eenvoudig')); ?> </h2>
                <ul class="order_process_guide">
                    <li>
                        <h3><?= $block->escapeHtml(__('Stap 1: Product kiezen')); ?></h3>
                        <p>
                            <span><?= $block->escapeHtml(__('Je kiest het type glas en voert de aantallen en afmetingen in.')); ?></span>
                        </p>
                        <p>
                            <a href="/keuzehulp/" class="btn btn-default"><span><?= $block->escapeHtml(__('Bekijk alle producten')); ?></span></a>
                        </p>
                    </li>
                    <li>
                        <h3><?= $block->escapeHtml(__('Stap 2: Direct meebestellen')); ?></h3>
                        <p>
                            <span><?= $block->escapeHtml(__('Je voegt de beglazingsmaterialen toe.')); ?></span>
                        </p>
                    </li>
                    <li>
                        <h3><?= $block->escapeHtml(__('Stap 3: Bestelling afronden')); ?></h3>
                        <p>
                            <span><?= $block->escapeHtml(__('Je kiest de gewenste leverdatum en betaalt op een veilige manier.')); ?></span>
                        </p>
                        <div id="gtx-trans" style="position: absolute; left: 367px; top: 21.7188px;">
                            <div class="gtx-trans-icon"></div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="embed-video">
                    <a data-fancybox data-src="https://www.youtube.com/embed/4acmf5VJcqc?rel=0">
                        <img src="https://www.glasgigant.nl/img/cms/youtube_1.jpg" alt="Video Thumbnail">
                    </a>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'Magento_Theme/js/jquery.fancybox.min'], function($) {
        $(document).ready(function() {
            $('[data-fancybox]').fancybox({
                type: 'iframe',
                Toolbar: false,
                iframe: {
                    preload: false,
                    css: {
                        border: '15px solid #ffffff',
                        top: '2%',
                        'border-radius': '4px'
                    }
                },
                afterLoad: function(instance, current) {
                    // Add custom close button
                    var closeButton = '<button data-fancybox-close class="custom-fancybox-close"><i class="fa fa-times-circle"></i></button>';
                    $(current.$content).append(closeButton);
                }
            });
        });
    });
</script>
