<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div id="homepage-slider-text" class="col-lg-4 col-lg-offset-8 col-md-4 col-md-offset-8">
    <div class="usp-wrapper">
        <div id="novi-usp">
            <div class="novi-usp">
                <div class="container">
                    <div class="owl-carousel owl-theme">
                        <div class="usp_item">
                            <div class="t">
                                <div class="c">
                                    <div class="usp-icon">
                                        <img src="<?= $block->getViewFileUrl('images/other_images/Achteraf-betalen.png') ?>" alt="title" class="img-responsive">
                                    </div>
                                    <div class="usp-content">
                                        <div class="title">
                                            <p><span><?= $block->escapeHtml(__('Veilig achteraf')) ?>,<span class="Apple-converted-space">&nbsp;</span></span><br><span><?= $block->escapeHtml(__('betalen')) ?></span></p>
                                        </div>
                                        <div class="subtitle">
                                            <p><span><?= $block->escapeHtml(__('Wil je je aankopen eerst geleverd hebben voordat je betaalt? Achteraf betalen doe je kosteloos met Billink. Wel zo veilig.')) ?></span></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="usp_item">
                            <div class="t">
                                <div class="c">
                                    <div class="usp-icon">
                                        <img src="<?= $block->getViewFileUrl('images/other_images/Gratis-productie.png') ?>" alt="title" class="img-responsive">
                                    </div>
                                    <div class="usp-content">
                                        <div class="title">
                                            <p><span><?= $block->escapeHtml(__('Gratis productie op')) ?>,<span class="Apple-converted-space">&nbsp;</span></span><br><span><?= $block->escapeHtml(__('maat vanaf € 1000')) ?></span></p>
                                        </div>
                                        <div class="subtitle">
                                            <p><span><?= $block->escapeHtml(__('Bestel je voor €1000 dan betaal je geen kleine ordertoeslag. Dat scheelt je €25,-!')) ?></span></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="usp_item">
                            <div class="t">
                                <div class="c">
                                    <div class="usp-icon">
                                        <img src="<?= $block->getViewFileUrl('images/other_images/Snelle-levering.png') ?>" alt="title" class="img-responsive">
                                    </div>
                                    <div class="usp-content">
                                        <div class="title">
                                            <p><span><?= $block->escapeHtml(__('Spoedleveringen')) ?>,<span class="Apple-converted-space">&nbsp;</span></span><br><span><?= $block->escapeHtml(__('vanaf 4 werkdagen')) ?></span></p>
                                        </div>
                                        <div class="subtitle">
                                            <p><span><?= $block->escapeHtml(__('Wil je snel je bestelling ontvangen? Spoedleveringen vanaf 4 werkdagen zijn mogelijk! Lekker snel.')) ?></span></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="usp_item">
                            <div class="t">
                                <div class="c">
                                    <div class="usp-icon">
                                        <img src="<?= $block->getViewFileUrl('images/other_images/Niet-goed-nieuwe-ruit.png') ?>" alt="title" class="img-responsive">
                                    </div>
                                    <div class="usp-content">
                                        <div class="title">
                                            <p><span><?= $block->escapeHtml(__('Niet goed')) ?>,<span class="Apple-converted-space">&nbsp;</span></span><br><span><?= $block->escapeHtml(__('nieuwe ruit')) ?></span></p>
                                        </div>
                                        <div class="subtitle">
                                            <p><span><?= $block->escapeHtml(__('Voldoet de ruit niet aan de kwaliteitsvoorschriften? Dan krijg je van ons direct een nieuwe. Snel en eenvoudig!')) ?></span></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="usp_item">
                            <div class="t">
                                <div class="c">
                                    <div class="usp-icon">
                                        <img src="<?= $block->getViewFileUrl('images/other_images/Gratis-verzending.png') ?>" alt="title" class="img-responsive">
                                    </div>
                                    <div class="usp-content">
                                        <div class="title">
                                            <p><span><?= $block->escapeHtml(__('Gratis levering')) ?> ,</span><br><span><?= $block->escapeHtml(__('op locatie')) ?></span></p>
                                        </div>
                                        <div class="subtitle">
                                            <p><span><?= $block->escapeHtml(__('Wil je je bestelling geleverd hebben. We leveren gratis door heel Nederland m.u.v. de Waddeneilanden. Dan hoef je niet te sjouwen.')) ?></span></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="usp_item">
                            <div class="t">
                                <div class="c">
                                    <div class="usp-icon">
                                        <img src="<?= $block->getViewFileUrl('images/other_images/Afleverdatum.png') ?>" alt="title" class="img-responsive">
                                    </div>
                                    <div class="usp-content">
                                        <div class="title">
                                            <p><span><?= $block->escapeHtml(__('Kies zelf je')) ?>,<span class="Apple-converted-space">&nbsp;</span></span><br><span><?= $block->escapeHtml(__('afleverdatum')) ?></span></p>
                                        </div>
                                        <div class="subtitle">
                                            <p><span><?= $block->escapeHtml(__('Je kiest zelf wanneer jij je glasbestelling wil ophalen of geleverd wil krijgen. Wel zo gemakkelijk.')) ?></span></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Theme/js/owl.carousel.min'
    ],function($) {
        $(document).ready(function () {
            $('.owl-carousel').owlCarousel({
                loop: true,
                margin: 10,
                nav: true,
                navText: [
                    '<i class="fa fa-angle-left" aria-hidden="true"></i>',
                    '<i class="fa fa-angle-right" aria-hidden="true"></i>',
                ],
                autoplay: true,
                // autoplaySpeed: 5000,
                autoplayTimeout: 5000,
                autoplayHoverPause:false,
                responsive: {
                    0: {
                        items: 2
                    },
                    600: {
                        items: 2
                    },
                    768: {
                        items: 3
                    },
                    992: {
                        items: 2
                    },
                    1024: {
                        items: 1
                    }
                }
            });
        });
    });
</script>
