<?php
/** @var $block \Magento\Framework\View\Element\Template */
?>
<div class="phone-wrapper-mobile">
    <span class="shop-phone">
        <i class="ico ico-16 ico-phone"></i>
        <?= $block->escapeHtml(__('Heeft u hulp nodig?')); ?> <strong><?= $block->escapeHtml(__('Bel')) ?>
            <a href="tel:0850511000"><?= $block->escapeHtml('0850511000') ?></a>
        </strong>
    </span>
</div>
