<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */
declare(strict_types=1);

namespace Geissweb\Euvat\Validator;

use Geissweb\Euvat\Api\Data\ValidationInterface;
use Geissweb\Euvat\Api\Data\ValidationResultInterface;
use Geissweb\Euvat\Helper\Functions;
use Geissweb\Euvat\Logger\Logger;
use Geissweb\Euvat\Model\Validation\ResultFactory;
use Geissweb\Euvat\Model\ValidationRepository;

/**
 * Class Service is a wrapper for the actual validation process through different validation services
 */
class Service
{
    /**
     * @var Hmrc
     */
    private $hmrcValidator;

    /**
     * @var Vies
     */
    private $viesValidator;

    /**
     * @var Logger
     */
    private $logger;

    /**
     * @var ValidationRepository
     */
    private $validationRepository;

    /**
     * @var Functions
     */
    private $helper;

    /**
     * @var ResultFactory
     */
    private $validationResultFactory;

    /**
     * Service constructor.
     * @param Hmrc $hmrcValidator
     * @param \Geissweb\Euvat\Validator\Vies $viesValidator
     * @param Functions $functionsHelper
     * @param ValidationRepository $validationRepository
     * @param ResultFactory $validationResultFactory
     * @param Logger $logger
     */
    public function __construct(
        Hmrc $hmrcValidator,
        Vies $viesValidator,
        Functions $functionsHelper,
        ValidationRepository $validationRepository,
        ResultFactory $validationResultFactory,
        Logger $logger
    ) {
        $this->hmrcValidator = $hmrcValidator;
        $this->viesValidator = $viesValidator;
        $this->logger = $logger;
        $this->validationRepository = $validationRepository;
        $this->helper = $functionsHelper;
        $this->validationResultFactory = $validationResultFactory;
    }

    /**
     * Validates a VAT number
     *
     * @param string $countryCode
     * @param string $vatNumber
     * @param bool $force
     *
     * @return ValidationResultInterface
     * @throws \SoapFault
     */
    public function validate(string $countryCode, string $vatNumber, bool $force = false): ValidationResultInterface
    {
        $this->logger->customLog("[Validating $countryCode $vatNumber]");

        //Estimate if we can reuse an existing validation
        $needToValidate = $this->helper->getNeedToValidate($countryCode.$vatNumber);
        $dbValidation = $this->validationRepository->getByVatId($countryCode.$vatNumber);
        if ($dbValidation instanceof ValidationInterface && !$force && !$needToValidate) {
            $isValid = (bool)$dbValidation->getVatIsValid();
            $isRequestSuccess = (bool)$dbValidation->getVatRequestSuccess();
            if ($isValid && $isRequestSuccess) {
                $dbValidation->setRequestMessage((string)__('The VAT number is valid.'));
            } elseif (!$isValid && $isRequestSuccess) {
                $dbValidation->setRequestMessage((string)__('The VAT number is invalid.'));
            }
            $response = $this->validationResultFactory->create();
            $response->setVatRequestDate($dbValidation->getVatRequestDate())
                ->setRequestMessage($dbValidation->getRequestMessage())
                ->setVatIsValid($isValid)
                ->setVatRequestSuccess($isRequestSuccess)
                ->setVatId($dbValidation->getVatId())
                ->setVatTraderName($dbValidation->getVatTraderName())
                ->setVatTraderAddress($dbValidation->getVatTraderAddress())
                ->setVatRequestCountryCode($countryCode);
            return $response;
        }

        switch ($countryCode) {
            case 'GB':
                $this->hmrcValidator->setParam('countryCode', $countryCode);
                $this->hmrcValidator->setParam('vatNumber', $vatNumber);
                $this->hmrcValidator->validate();
                $response = $this->hmrcValidator->getResult();
                break;
            default:
                $this->viesValidator->setParam('countryCode', $countryCode);
                $this->viesValidator->setParam('vatNumber', $vatNumber);
                $this->viesValidator->validate();
                $response = $this->viesValidator->getResult();
                break;
        }

        return $response;
    }
}
