<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_Faqs
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Question page tag block
 *
 * @var $block Bss\Faqs\Block\ModuleBlock
 */
$moduleConfig = $block->getModuleConfig();
?>
<div class="faq_tag_block">
    <div class="tag_block_label">
        <div><?php echo __('TAG: '); ?></div>
    </div>
    <i class="fa fa-spinner fa-pulse" aria-hidden="true"></i>
</div>
<script type="text/x-magento-init">
    {
        ".faq_tag_block": {
            "bss_faqs_question_tag": {
                "baseUrl": "<?php echo $moduleConfig->getBaseUrl(); ?>",
                "faqid": <?php echo $block->getFaqId(); ?>
            }
        }
    }
</script>
