<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_Faqs
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Searchbar block
 *
 * @var $block Bss\Faqs\Block\Searchbar
 */
$moduleConfig = $block->getModuleConfig();
?>
<div class="faq_searchbar_block">
    <form action="<?php echo $moduleConfig->getBaseUrl(); ?>faqs/search/result/" id="faq_search">
    <input type="hidden" name="category" value="<?php echo $block->getCategoryId() ?>">
    <button class="faq_search_submit" type="submit" form="faq_search">
        <i class="fa fa-search" aria-hidden="true"></i>
    </button>
    <input id="faq_search_textfield" type="text" name="keyword" />
    </form>
</div>
<script type="text/x-magento-init">
    {
        ".faq_searchbar_block": {
            "bss_faqs_searchbar_control": {
            }
        }
    }
</script>
