<?php
/**
 * @var \Fooman\PdfCustomiser\Block\Comments $block
 */
?>
<?php if ($block->getCustomComments()): ?>
	
    <table class="amasty-attributes" border="0" cellspacing="0">
        <?php foreach ($block->getCustomComments() as $comment): ?>
            <?php if ($comment['label']): ?>
                <tr>
                    <td><?= /* @noEscape */ $block->escapeComment($comment['label']) ?>: <?= /* @noEscape */ $block->escapeComment($comment['value']) ?></td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>

    <br/>
<?php endif; ?>
<?php if ($block->getComments()): ?>
    <br/>
    <strong><?= $block->escapeHtml(__('Comments')) ?></strong><br/>
    <table border="0" cellpadding="2" cellspacing="0">
        <?php foreach ($block->getComments() as $comment): ?>
            <tr>
                <td><?= /* @noEscape */ $block->escapeComment($comment['comment']) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <br/>
<?php endif; ?>