<?php
/**
 * Mico Solutions EULA
 * http://www.micosolutions.com/
 * Read the license at http://www.micosolutions.com/license.txt
 *
 *
 * @category    Mico
 * @package     Mico_Cmp
 * @copyright   Copyright (c) 2011 Mico Solutions (http://www.micosolutions.com)
 * @license     http://www.micosolutions.com/license.txt
 */
 
/**
 * Mico Cmp module
 *
 * @author		Pham Tri Cong <phtcong@micosolutions.com>
 */
?><!-- micosolutions cmp --><?php
$config = $this->getProductConfig();
if (!$config) {
	echo '<!-- no cmp config-->';
	return "";
}
?>
<div id="cmp-log"></div>

<script type="text/javascript">	
//<![CDATA[
require(['jquery','cmputils','cmp','Magento_Catalog/js/price-utils'], function(jQuery,cmpUtils, cmp, priceUtils){
	//micoCmpQtyKeyup = 1;
	//micoCmpPriceItem = '';'#product_addtocart_form .product-info-price .price';
	//_mico_cmp_timer_seconds = 100;
	micoPriceUtil = priceUtils;
	micoCmpZeroPriceText = '<?php echo __('Please choose options')?>';
	micoCustomMathPricing = new MicoCustomMathPricing(<?php echo json_encode($config)?>);
	micoPrintsizePriceLogic = 0;
	var cmpItem = jQuery('#cmp-log');
	cmpItem.cmp();
	_MICO_INIT_PRICE = 1;
});
//]]>
</script><!-- /micosolutions cmp -->