<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var \Superiortile\RequiredProduct\Block\Product\View\RequiredProducts $block
 * @var \Magento\Framework\Escaper $escaper
 */

?>
<div class="required-products-block" id="required-products-block">
    <span class="title"><?= /** @noEscape */ __('Related Products') ?></span>
    <?= /** @noEscape */ $block->getChildHtml() ?>
</div>
<div id="required-product-detail"></div>
<div class="required-subtotals" data-bind="scope:'required-subtotals'">
    <!-- ko if: totals().totalQty -->
    <span class="label">
        <!-- ko text: label.replace('%s', totals().totalQty) --><!-- /ko -->
    </span>
    <span class="total">
        <!-- ko text: totals().formattedPrice --><!-- /ko -->
    </span>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        ".required-subtotals": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "required-subtotals": {
                        "component": "Superiortile_RequiredProduct/js/product/totals"
                    }
                }
            }
        }
    }
</script>
