<?php
$menuItemId = $block->getData('menu_item_id');
$category_checkbox = $block->getData('category_checkBox');
$category_vertical_menu_checkbox = $block->getData('category_vertical_menu_checkbox');
$category_vertical_bg_color = $block->getData('category_vertical_bg_color');
$currentItem = $block->getData('current_item');
$currentMenuDesignType = $block->getData('current_menu_design_type');
$product_display_checkbox = $block->getData('product_display_checkbox');
$open_in_new_tab_checkbox = $block->getData('open_in_new_tab_checkbox');
$vertical_bg_color = $category_vertical_menu_checkbox ? '' : 'hidden';
?>
<div class="menuColumnBlockWrapper" style="margin:10px 0;">
    <div class="col-m-4 category_checkbox_wrapper menu-item-option">
        <input class="admin__control-checkbox checkbox category_checkbox"
               id="menu_data_<?= $menuItemId ?>_subcat"
               type="checkbox"
               name="menu_data[<?= $menuItemId ?>][subcat]" <?= $category_checkbox ?> >
        <label for="menu_data_<?= $menuItemId ?>_subcat"
               class="admin__field-label"
               style="line-height:16px;"><?= __('Display all subcategories') ?></label>
    </div>
    <?php if ($currentMenuDesignType == 'horizontal'): ?>
        <div class="col-m-4 category_checkbox_wrapper menu-item-option">
            <input id="menu_data_<?= $menuItemId ?>_verticalsubcat"
                   class="admin__control-checkbox checkbox vertical_category_checkbox"
                   type="checkbox"
                   name="menu_data[<?= $menuItemId ?>][verticalsubcat]" <?= $category_vertical_menu_checkbox ?>>
            <label for="menu_data_<?= $menuItemId ?>_verticalsubcat"
                   class="admin__field-label"
                   style="line-height:16px;"><?= __('Display Vertical Menu') ?></label>
        </div>
        <div class="col-m-4 vertical_category_color_wrapper menu-item-option <?= $vertical_bg_color ?>">
            <label for="menu_data_<?= $menuItemId ?>_verticalcatcolor"
                   class="admin__field-label"
                   style="line-height:16px;"><?= __('Vertical Menu Background Color') ?></label>
            <input id="menu_data_<?= $menuItemId ?>_verticalcatcolor"
                   class="jscolor admin__control-text vertical_category_color"
                   type="text"
                   name="menu_data[<?= $menuItemId ?>][verticalcatcolor]"
                   value="<?= $category_vertical_bg_color ?>">
        </div>
    <?php endif; ?>
    <?php if ($currentMenuDesignType == 'horizontal' || $currentMenuDesignType == 'horizontal-vertical'): ?>
    <div class="col-m-4 category_checkbox_wrapper menu-item-option">
        <input id="menu_data_<?= $menuItemId ?>_product_display"
          class="admin__control-checkbox checkbox product_display_checkbox"
          type="checkbox"
          name="menu_data[<?= $menuItemId ?>][product_display]" <?= $product_display_checkbox ?> >
        <label for="menu_data_<?= $menuItemId ?>_product_display"
               class="admin__field-label"
               style="line-height:16px;"><?= __('Display Product Items') ?></label>
    </div>
    <?php endif; ?>
    <div class="col-m-4 open_in_new_tab_checkbox_wrapper menu-item-option">
        <input id="menu_data_<?= $menuItemId ?>_open_in_new_tab"
          class="admin__control-checkbox checkbox open_in_new_tab_checkbox"
          type="checkbox"
          name="menu_data[<?= $menuItemId ?>][open_in_new_tab]" <?= $open_in_new_tab_checkbox ?> >
        <label for="menu_data_<?= $menuItemId ?>_open_in_new_tab"
               class="admin__field-label"
               style="line-height:16px;"><?= __('Open In New Tab') ?></label>
    </div>
</div>
<div class="cf"></div>
<?php $hidden = ""; ?>
<?php if (!$category_checkbox && !$product_display_checkbox): ?>
    <?php $hidden = "hidden"; ?>
<?php endif; ?>
<?php if ($category_checkbox): ?>
<div class="menuColumnBlockWrapper child-category-settings <?= $hidden ?>" style="margin:10px 0;">
    <div class="col-m-3 category_checkbox_wrapper category_exclude">
        <div class="verical_category_child">
            <label for="menu_data_<?= $menuItemId ?>_verticalcatexclude"
                   class="admin__field-label"
                   style="line-height:16px;"><?= __('Exclude child category') ?></label>
            <input id="menu_data_<?= $menuItemId ?>_verticalcatexclude"
                   class="admin__control-text vertical_category_exclude"
                   type="text"
                   name="menu_data[<?= $menuItemId ?>][verticalcatexclude]"
                   value="<?= $currentItem->getData('vertical_cat_exclude') ?>">
            <p><?=  __('Enter comma seperated category ids eg. 25,26,27'); ?></p>
        </div>
    </div>
    <div class="col-m-3 category_checkbox_wrapper category_sort_by">
        <div class="verical_category_child">
            <label for="menu_data_<?= $menuItemId ?>_verticalcatsortby"
                   class="admin__field-label"
                   style="line-height:16px;"><?= __('Category Sort By') ?></label>
            <select id="menu_data_<?= $menuItemId ?>_verticalcatsortby"
                class="admin__control-select vertical_category_sortby"
                name="menu_data[<?= $menuItemId ?>][verticalcatsortby]">
                <option value="position" <?= $currentItem->getData('vertical_cat_sortby') == 'position' ? "selected" : ""?>>Position</option>
                <option value="name" <?= $currentItem->getData('vertical_cat_sortby') == 'name' ? "selected" : ""?>>Name</option>
            </select>
        </div>
    </div>
    <div class="col-m-3 category_checkbox_wrapper category_sort_order">
        <div class="verical_category_child">
            <label for="menu_data_<?= $menuItemId ?>_verticalcatsortorder"
                   class="admin__field-label"
                   style="line-height:16px;"><?= __('Category Sort Order') ?></label>
            <select id="menu_data_<?= $menuItemId ?>_verticalcatsortorder"
                    class="admin__control-select vertical_category_sortorder"
                    name="menu_data[<?= $menuItemId ?>][verticalcatsortorder]">
                <option value="asc" <?= $currentItem->getData('vertical_cat_sortorder') == 'asc' ? "selected" : ""?>>ASC</option>
                <option value="desc" <?= $currentItem->getData('vertical_cat_sortorder') == 'desc' ? "selected" : ""?>>DESC</option>
            </select>
        </div>
    </div>
    <div class="col-m-3 category_checkbox_wrapper category_depth">
        <div class="verical_category_child">
            <label for="menu_data_<?= $menuItemId ?>_verticalcatlevel"
                   class="admin__field-label"
                   style="line-height:16px;"><?= __('Child Category Depth') ?></label>
            <select id="menu_data_<?= $menuItemId ?>_verticalcatlevel"
                    class="admin__control-select vertical_category_level"
                    name="menu_data[<?= $menuItemId ?>][verticalcatlevel]">
                <option value="2" <?= $currentItem->getData('vertical_cat_level') == '2' ? "selected" : ""?>>2</option>
                <option value="3" <?= $currentItem->getData('vertical_cat_level') == '3' ? "selected" : ""?>>3</option>
                <option value="4" <?= $currentItem->getData('vertical_cat_level') == '4' ? "selected" : ""?>>4</option>
                <option value="5" <?= $currentItem->getData('vertical_cat_level') == '5' ? "selected" : ""?>>5</option>
            </select>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($product_display_checkbox): ?>
<div class="menuColumnBlockWrapper child-category-settings <?= $hidden ?>" style="margin:10px 0;">
    <div class="col-m-3 category_checkbox_wrapper category_exclude">
        <div class="verical_category_child">
            <label for="menu_data_<?= $menuItemId ?>_verticalcatexclude"
                   class="admin__field-label"
                   style="line-height:16px;"><?= __('Exclude Product Items') ?></label>
            <input id="menu_data_<?= $menuItemId ?>_verticalcatexclude"
                   class="admin__control-text vertical_category_exclude"
                   type="text"
                   name="menu_data[<?= $menuItemId ?>][verticalcatexclude]"
                   value="<?= $currentItem->getData('vertical_cat_exclude') ?>">
            <p><?= __('Enter comma seperated product ids eg. 25,26,27'); ?></p>
        </div>
    </div>
    <div class="col-m-3 category_checkbox_wrapper category_sort_by">
        <div class="verical_category_child">
            <label for="menu_data_<?= $menuItemId ?>_verticalcatsortby"
                   class="admin__field-label"
                   style="line-height:16px;"><?= __('Product Sort By') ?></label>
            <select id="menu_data_<?= $menuItemId ?>_verticalcatsortby"
                class="admin__control-select vertical_category_sortby"
                name="menu_data[<?= $menuItemId ?>][verticalcatsortby]">
                <option value="position" <?= $currentItem->getData('vertical_cat_sortby') == 'position' ? "selected" : ""?>>Position</option>
                <option value="name" <?= $currentItem->getData('vertical_cat_sortby') == 'name' ? "selected" : ""?>>Name</option>
            </select>
        </div>
    </div>
    <div class="col-m-3 category_checkbox_wrapper category_sort_order">
        <div class="verical_category_child">
            <label for="menu_data_<?= $menuItemId ?>_verticalcatsortorder"
                   class="admin__field-label"
                   style="line-height:16px;"><?= __('Product Sort Order') ?></label>
            <select id="menu_data_<?= $menuItemId ?>_verticalcatsortorder"
                    class="admin__control-select vertical_category_sortorder"
                    name="menu_data[<?= $menuItemId ?>][verticalcatsortorder]">
                <option value="asc" <?= $currentItem->getData('vertical_cat_sortorder') == 'asc' ? "selected" : ""?>>ASC</option>
                <option value="desc" <?= $currentItem->getData('vertical_cat_sortorder') == 'desc' ? "selected" : ""?>>DESC</option>
            </select>
        </div>
    </div>
</div>
<?php endif; ?>
