<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Controller\Adminhtml\Setup;

use Geissweb\Euvat\Helper\Compat\JsonFactory;
use Magento\Backend\App\Action\Context;
use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\App\Response\Http\FileFactory;
use Geissweb\Euvat\Model\System\TechReport as TechReportModel;

/**
 * Generates download response for techreport.json file
 */
class TechReport extends \Magento\Backend\App\Action
{
    /**
     * Authorization level of a basic admin session
     * @see _isAllowed()
     */
    const ADMIN_RESOURCE = 'Geissweb_Euvat::techreport';

    /**
     * @var \Magento\Framework\App\Response\Http\FileFactory
     */
    private $fileFactory;

    /**
     * @var \Geissweb\Euvat\Model\System\TechReport
     */
    private $techReport;
    /**
     * @var \Geissweb\Euvat\Helper\Compat\JsonFactory
     */
    private $jsonFactory;

    /**
     * Initialize Controller
     *
     * @param \Magento\Backend\App\Action\Context $context
     * @param \Magento\Framework\App\Response\Http\FileFactory $fileFactory
     * @param \Geissweb\Euvat\Model\System\TechReport $techReport
     */
    public function __construct(
        Context $context,
        FileFactory $fileFactory,
        TechReportModel $techReport,
        JsonFactory $jsonFactory
    ) {
        parent::__construct($context);
        $this->fileFactory = $fileFactory;
        $this->techReport = $techReport;
        $this->jsonFactory = $jsonFactory;
    }

    /**
     * Downloads the tech report file
     */
    public function execute()
    {
        return $this->fileFactory->create(
            'euvat-techreport-'.date("YmdHis").'.json',
            $this->getJson(),
            DirectoryList::TMP
        );
    }

    /**
     * Generates the file content
     * @return bool|string
     */
    protected function getJson()
    {
        /** @var \Magento\Framework\Serialize\Serializer\Json $json */
        $json = $this->jsonFactory->create();
        try {
            return $json->serialize([
                'system_info' => $this->techReport->getSystemInfo(),
                'stores' => $this->techReport->getStoresInformation(),
                'groups' => $this->techReport->getCustomerGroups(),
                'config' => $this->techReport->getConfiguration(),
                'tax_classes' => $this->techReport->getTaxClasses(),
                'tax_rules' => $this->techReport->getTaxRules(),
                'tax_rates' => $this->techReport->getTaxRates()
            ]);
        } catch (\Exception $e) {
            return $json->serialize((array)$e);
        }
    }

    /**
     * @return bool
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed(self::ADMIN_RESOURCE);
    }
}
