<?php
use \RedChamps\WeightDisplay\Model\Config\Source\Checkout\Position;
?>
<?php
/** @var $block \RedChamps\WeightDisplay\Block\Checkout\OnePage**/
?>
<?php $allowedPosition = $block->getPosition();?>
<?php if (($allowedPosition == Position::BOTH || $allowedPosition == $block->getPositionType()) && $weight = $block->getTotalWeight()):?>
    <div class="cart-totals total-weight my-6">
        <table class="w-full data table totals">
            <tbody>
            <tr class="grand totals excl">
                <th class="text-left mark inline-block" scope="row">
                    <strong><?= $block->getTotalLabel();?></strong>
                </th>
                <td class="text-right amount">
                    <strong><span class="price"><?= $weight?></span></strong>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
<?php endif;?>
