<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="contact-us-page">

    <div class="row form-contact">
</div>
<div class="col-lg-12 col-md-12">
	<form class="form contact"
          action="<?php /* @escapeNotVerified */
		  echo $block->getFormAction(); ?>"
          id="contact-form"
          method="post"
          data-hasrequired="<?php /* @escapeNotVerified */
		  echo __('* Required Fields') ?>"
          data-mage-init='{"validation":{}}'>
		<fieldset class="fieldset">
		
				<h2><?php /* @escapeNotVerified */
					echo __('Contactformulier') ?></h2>
			
			<div class="left-input" style="margin-top:18px">
				<div class="field name required">
					<div class="control">
						<input placeholder="<?php echo __('Naam*') ?>" name="name" id="name" title="<?php /* @escapeNotVerified */
						echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
					</div>
				</div>
				<div class="field email required">
					<div class="control">
						<input placeholder="<?php echo __('E-mailadres*') ?>" name="email" id="email" title="<?php /* @escapeNotVerified */
						echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
					</div>
				</div>
				<div class="field telephone">
					<div class="control">
						<input placeholder="<?php echo __('Telefoonnummer') ?>" name="telephone" id="telephone" title="<?php /* @escapeNotVerified */
						echo __('Phone Number') ?>" value="" class="input-text" type="text"/>
					</div>
				</div>
			</div>
			<div class="field comment required">
				<div class="control">
					<textarea placeholder="<?php echo __('Bericht*') ?>" name="comment" id="comment" title="<?php /* @escapeNotVerified */
					echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
				</div>
			</div>
			<?php echo $block->getChildHtml('form.additional.info'); ?>
		</fieldset>
		<div class="actions-toolbar">
			<div class="primary">
				<input type="hidden" name="hideit" id="hideit" value=""/>
				<button type="submit" title="<?php /* @escapeNotVerified */
				echo __('Send Message') ?>" class="action submit primary">
					<span><?php /* @escapeNotVerified */
						echo __('Bericht versturen') ?></span>
				</button>
			</div>
		</div>
	</form>
</div>
</div>
</div>


