<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();

    /* Demo Attributes */
    $levertijd = $_product->getAttributeText('levertijd_indicatie');
?>

    <div class="fieldset">
      <div class="row">
        <?php if ($block->shouldRenderQuantity()): ?>
          <div class="col-2">
            <div class="field qty">
            <div class="control control-qty-cart">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */
					   echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */
					   echo __('Qty') ?>" class="qty-default input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                />

            </div>
        </div>
      </div>
		<?php endif; ?>
    <div class="col-10">
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */
					echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */
					echo $buttonTitle ?></span>
            </button>
			<?php echo $block->getChildHtml('', true) ?>
			<div class="levertijd-container"><div class="levertijd"><?php if( $levertijd != '' ) { echo __('<span class="levertijd-label">Levertijd:</span> &plusmn; ') . $levertijd; } else { echo ''; } ?></div></div>
        </div>
      </div>
    </div>
    </div>
</div>
<?php endif; ?>