<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $stockRegistry = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface');
    $stockItem=$stockRegistry->getStockItem($_product->getId());

    $_product = $block->getProduct();
    $productQty = $_product->getExtensionAttributes()->getStockItem()->getQty();

    /* Demo Attributes */
    $levertijd = $_product->getAttributeText('levertijd_indicatie');
?>

    <div class="fieldset">
      <div class="row">
        <?php if ($block->shouldRenderQuantity()): ?>
          <div class="col-2">
            <div class="field qty">
            <div class="control control-qty-cart">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */
					   echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */
					   echo __('Qty') ?>" class="qty-default input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                />

            </div>
        </div>
      </div>
		<?php endif; ?>
    <div class="col-10">
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */
					echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */
					echo $buttonTitle ?></span>
            </button>
			<?php echo $block->getChildHtml('', true) ?>
            <?php $levertijd_link = '' . $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link-levertijden')->toHtml() . '' ?>
            <?php
                if ($stockItem->getData('manage_stock')) {
                    if ($productQty > 0 && $productQty < 100) {
                        //op voorraad(aantal stuks)
                        $inStock =  '<div class="col-md-6 mt-2" style="color:green;"><span>Op voorraad (' . $productQty . ') stuks </span></div>';
                    } 
                    elseif ($productQty > 99) { 
                        //op voorraad
                        $inStock = '<div class="col-md-6 mt-2" style="color:green;"><span>Op voorraad</span></div>';
                    } 
                    else {
                        //geen 'op voorraad' melding
                        $inStock = '';
                    }
                }
                else {
                    $inStock = '';
                }

                //als er geen levertijd ingevoerd is, 'actuele levertijd' tekst neerzetten
                if ($levertijd == '') {
                    $levertijd = 'Actuele levertijd';
                }

                echo '<div class="d-flex">' . $inStock . ' <div class="col-md-12 ml-4 mt-2"><i class="fas fa-truck fa-lg" style="color: #004562;"></i><a href="#" id="click-me-levertijd" style="text-decoration:underline;"><strong> ' . $levertijd . '</strong></a>' . $levertijd_link . '</div></div>';
            ?>
        </div>
      </div>
    </div>
    </div>
</div>
<?php endif; ?>