<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Order Archive for Magento 2
*/
?>
<div class="pp-buttons-container">
    <p>
        <button class="primary" id="<?php echo $block->getHtmlId() ?>" onclick="setLocation('<?php echo $block->getAjaxArchivingUrl() ?>')" type="button">
            <?php echo __('Archiving') ?>
        </button>
    </p>
</div>