<style>
    .account .cart-right, .account .crosssell-container {display:none;}
    
    .account .cart-left.col-md-9 {flex: 0 0 100%;
        max-width: 100%;}
    .account .restore-shared-cart {
        width:inherit;    
        font-size: 18px !important;
        height: 44px;
        padding-bottom: 2px !important;
        border-bottom: 1px solid rgba(0, 0, 0, 0.35) !important;
        text-transform:none;
    }
    .account .cart-left table thead th:nth-child(2) {text-align:center;}
    .account .share-cart-popup.share-cart-email-popup {width:100%!important;}
    .account .cart.main.actions, .account .actions-toolbar {display:none;}
    .account .restore-shared-cart {padding:0px 80px!important;}
    .account .btn-primary, .account .btn-primary:not(:disabled):not(.disabled):active {background-color: #f47727;}
    .account .btn-primary:hover {background-color: #444;}
    .account .cart.table-wrapper .product-item-details {text-align:left;}

</style>