
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Catalog\Model\Product $_product
 * @var \Bss\RequiredProduct\Block\Product\View\Items $block
 * @var \Magento\Catalog\Model\ResourceModel\Product\Link\Product\Collection $collection
 */
$collection = $block->getProductCollection();
$image = 'related_products_list';
?>

<?php if (count($collection)): ?>
    <?php foreach ($collection as $_product): ?>
        <div class="item product product-item required-item"

            data-product-id="<?= $escaper->escapeHtmlAttr($_product->getId()) ?>">
            <div class="product-info-container" data-product-id="<?= $escaper->escapeHtmlAttr($_product->getId()) ?>">
                <div class="product-item-info">
                    <a href="#" class="product photo product-item-photo">
                        <?= $block->getImage($_product, $image)->toHtml() ?>
                    </a>
                </div>
                <div class="product details product-item-details">
                    <strong class="product name product-item-name">
                        <?= $escaper->escapeHtml($_product->getName()) ?>
                    </strong>
                    <div class="product-item-attributes">
                        <?= /* @noEscape */ $block->getProductAttributesHtml($_product) ?>
                    </div>
                </div>
            </div>
            <?= /* @noEscape */ $block->getProductPrice($_product) ?>
            <div class="product-add-form" style="text-align: center">
                <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                      action="<?= $escaper->escapeUrl($block->getUrl('requiredproduct/product/add/')) ?>" method="post"
                      id="product_addtocart_form_<?= $_product->getId() ?>">
                    <?= $block->getBlockHtml('formkey') ?>
                    <?= $block->getChildHtml('form_top') ?>
                    <?= $block->getChildHtml('form_bottom') ?>
                    <div class="actions">
                        <button type="submit"
                                title="<?= $block->escapeHtmlAttr('Meebestellen') ?>"
                                class="action primary tocart <?= $block->canImmediatelyAddToCart($_product) ? '' : 'can-not-add' ?>"
                                disabled
                                id="product-addtocart-button">
                            <span><?= $block->escapeHtml('Meebestellen') ?></span>
                        </button>
                        <?= $block->getChildHtml('', true) ?>
                    </div>
                </form>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Bss_RequiredProduct/js/product/view/validate-product": {}
        }
    }
</script>