<?php /** @var $block \RedChamps\WeightDisplay\Block\Checkout\OnePage **/?>
<script>
    <?php if ($block->isEnabled()):?>
    window.cartWeight = {
        active: true,
        position:"<?= $block->getPosition()?>",
        label:"<?= $block->getTotalLabel()?>",
        amount: "<?= $block->getTotalWeight()?>",
    };
    <?php else:?>
    window.cartWeight = {
        active:false
    };
    <?php endif;?>
</script>

