<?php if ($block->getHelper()->supportCookieDirective()):?>
    
	<script data-ommit="true">

		(function()
		{
			document.addEventListener("DOMContentLoaded", () => 
			{
				AEC.CookieConsent.setWidget(<?php echo json_encode([ 'display' => $block->getHelper()->getKeepCookieWidget(), 'color' => $block->getHelper()->getKeepCookieWidgetColor(),'colorEnd' => $block->getHelper()->getKeepCookieWidgetColorEnd() ]) ?>).setEndpoints(<?php echo json_encode([ 'type' => 'json', 'cookie' => $block->getUrl('datalayer/index/cookie'), 'cookieContent' => $block->getUrl('datalayer/index/cookieContent'), 'cookieConsent' => $block->getUrl('datalayer/index/cookieConsent') ]) ?>).getConsentDialog(dataLayer);
			});
		})();
		
	</script>
	
<?php endif ?>