<?php
/**
* Copyright © 2016 Magento. All rights reserved.
* See COPYING.txt for license details.
*/
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
* Product list template
* @var $block \Magento\Catalog\Block\Product\ListProduct
*/
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_config            = $this->helper('Sm\Market\Helper\Data');
$homeStyle          = $_config->getThemeLayout('home_style');
$_priceHelper       = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
  <div class="message info empty"><div><?php /* @escapeNotVerified */
  echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
  <div class="toolbar-top">
    <?php echo $block->getToolbarHtml() ?>
  </div>
  <?php echo $block->getAdditionalHtml() ?>
  <?php
  if ($block->getMode() == 'grid') {
    $viewMode        = 'grid';
    $image           = 'category_page_grid';
    $showDescription = false;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
  } else {
    $viewMode        = 'list';
    $image           = 'category_page_list';
    $showDescription = true;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
  }
  /**
  * Position for actions regarding image size changing in vde if needed
  */
  $pos = $block->getPositioned();
  ?>
  <div class="category-product products wrapper <?php /* @escapeNotVerified */
  echo $viewMode; ?> products-<?php /* @escapeNotVerified */
  echo $viewMode; ?>">
  <?php $iterator = 1; ?>

  <?php if ($viewMode == 'grid') { ?>

    <div class="row">
      <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
      <?php foreach ($_productCollection as $_product): ?>
        <div class="col-sm-6 col-lg-4">
          <div class="product-grid_card" data-container="product-grid">
            <div class="row">
              <div class="col-4 col-sm-12 product-card_image-container">
                <?php $productImage = $block->getImage($_product, $image); ?>

                <!--LABEL PRODUCT-->

                <?php
                $orgprice             = $_product->getPrice();
                $specialprice         = $_product->getSpecialPrice();
                $specialPriceFromDate = $_product->getSpecialFromDate();
                $specialPriceToDate   = $_product->getSpecialToDate();

                $today = time();

                if ($specialprice && $_config->getAdvanced('show_salelabel')) {
                  if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                    <?php if ($specialprice < $orgprice) {
                      $save_percent = 100 - round(($specialprice / $orgprice) * 100);
                      ?>
                      <div class="product-card_badges label-product">
                        <!-- <span class="sale-product-icon">
                          <?php 
                          /* echo '-' . $save_percent . '%'; */
                          ?>
                        </span> -->
                        <span class="text">
                          <div class="sale-product-icon"></div>
                        </span>
                      </div>
                    <?php } ?>
                  <?php }
                }
                ?>

                <!--END LABEL PRODUCT-->
                <a href="<?php /* @escapeNotVerified */
                echo $_product->getProductUrl() ?>" tabindex="-1">
                <?php echo $productImage->toHtml(); ?>
              </a>
            </div>
            <div class="col-8 col-sm-12 product-card_details">
              <div class="product-card_title">
                <?php
                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                ?>
                <a href="<?php /* @escapeNotVerified */
                echo $_product->getProductUrl() ?>">
                <?php /* @escapeNotVerified */
                echo $_helper->productAttribute($_product,mb_strimwidth($_product->getName(), 0, 78, "..."), 'name'); ?>
              </a>
            </div>
            <div class="product-card_details-list">
              <?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('detailslisting')->getFrontend()->getValue($_product); ?>
            </div>
            <div class="row">
              <div class="col-md-7 col-6 pr-0">
                <?php if ($_product->getPriceInfo()->getPrice('final_price')): ?>
                  <div class="price-box price-final_price">
                    <span class="normal-price">
                      <span class="price-container price-final_price tax weee">
                          <?php $priceExcl = $_product->getPriceInfo()->getPrice('final_price')->getMaximalPrice()->getValue() / 1.21; ?>
                          <?php if ($priceExcl != 0): ?>
                          <span class="price" style="font-size:14px;">
                          € <?php /* @escapeNotVerified */ echo number_format(round($priceExcl, 2),2, ',', '.'); ?> 
                          </span>
                          <span>excl. BTW</span>
                          <br />
                          <span class="price">
                              € <?php /* @escapeNotVerified */ echo number_format(round($_product->getPriceInfo()->getPrice('final_price')->getMaximalPrice()->getValue(),2),2, ',', '.') ?> 
                          </span> 
                          <span>incl. BTW</span>
                          <?php endif; ?>
                      </span>
                    </span>
                  </div>
                <?php endif; ?>
              </div>
              <div class="col-md-5 col-6 mt-auto">
                <div class="product-card_view-product bekijken">
                  <a href="<?php /* @escapeNotVerified */	echo $_product->getProductUrl() ?>"><span>Bekijken</span></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
</div>

<?php } else { ?>
  <ol class="products list items product-items">
    <?php foreach ($_productCollection as $_product): ?>
      <li class="item respl-item-list product product-item">
        <div class="product-item-info" data-container="product-grid">
          <div class="item-inner">
            <div class="box-image-list">
              <?php $productImage = $block->getImage($_product, $image); ?>

              <!--LABEL PRODUCT-->

              <?php
              $specialprice         = $_product->getSpecialPrice();
              $specialPriceFromDate = $_product->getSpecialFromDate();
              $specialPriceToDate   = $_product->getSpecialToDate();

              $today = time();

              if ($specialprice && $_config->getAdvanced('show_salelabel')) {
                if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                  <div class="label-product label-sale">
                    <span class="sale-product-icon">
                      <?php echo __('Sale'); ?>
                    </span>
                  </div>
                <?php }
              }
              ?>

              <!--END LABEL PRODUCT-->

              <a href="<?php /* @escapeNotVerified */
              echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
              <?php echo $productImage->toHtml(); ?>
            </a>

          </div>

          <div class="product details product-item-details box-info-list">
            <?php
            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
            ?>
            <h2 class="product name product-item-name product-name">
              <a class="product-item-link" href="<?php /* @escapeNotVerified */
              echo $_product->getProductUrl() ?>">
              <?php /* @escapeNotVerified */
              echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
            </a>
          </h2>

          <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
          <?php /* @escapeNotVerified */
          echo $block->getProductPrice($_product) ?>
          <?php echo $block->getProductDetailsHtml($_product); ?>

          <div class="product-item-inner">
            <?php if ($showDescription): ?>
              <div class="product description product-item-description">
                <?php /* @escapeNotVerified */
                echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                <a href="<?php /* @escapeNotVerified */
                echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                echo $_productNameStripped ?>"
                class="action more"><?php /* @escapeNotVerified */
                echo __('Learn More') ?></a>
              </div>
            <?php endif; ?>
          </div>

          <div class="bottom-action">
            <?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
              <?php if ($_product->isSaleable()): ?>
                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                echo $postParams['action']; ?>" method="post">
                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                echo $postParams['data']['product']; ?>">
                <input type="hidden" name="<?php /* @escapeNotVerified */
                echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
                echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                <?php echo $block->getBlockHtml('formkey') ?>
                <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart btn-action btn-cart">
                  <span><?php /* @escapeNotVerified */
                  echo __('Add to Cart') ?></span>
                </button>
              </form>
            <?php else: ?>
              <?php if ($_product->getIsSalable()): ?>
                <div class="stock available"><span><?php /* @escapeNotVerified */
                echo __('In stock') ?></span></div>
              <?php else: ?>
                <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
                echo __('Out of stock') ?></span></div>
              <?php endif; ?>
            <?php endif; ?>
          <?php } ?>

          <div class="add-to-links" data-role="add-to-links" class="actions-secondary">
            <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
              <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
                echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                <span><?php /* @escapeNotVerified */
                echo __('Add to Wish List') ?></span>
              </a>
            <?php endif; ?>
          <?php } ?>

          <?php if ($_config->getAdvanced('show_compare_button')) { ?>
            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
            <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
            echo $compareHelper->getPostDataParams($_product); ?>' role="button">
            <span><?php /* @escapeNotVerified */
            echo __('Add to Compare') ?></span>
          </a>
        <?php } ?>
      </div>
    </div>
  </div>
</div>
</div>
</li>
<?php endforeach; ?>
</ol>
<?php } ?>
</div>
<div class="toolbar-bottom">
  <?php echo $block->getToolbarHtml() ?>
</div>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
  <script type="text/x-magento-init">
  {
    "[data-role=tocart-form], .form.map.checkout": {
      "catalogAddToCart": {}
    }
  }
  </script>
<?php endif; ?>
<?php endif; ?>
