<?php
/**
 * MageVision Update Order Email Address Extension
 *
 * @category     MageVision
 * @package      MageVision_UpdateOrderEmailAddress
 * @author       MageVision Team
 * @copyright    Copyright (c) 2018 MageVision (http://www.magevision.com)
 * @license      LICENSE_MV.txt or http://www.magevision.com/license-agreement/
 */
?>
<?php
$order = $block->getOrder();

$orderAdminDate = $block->formatDate(
    $block->getOrderAdminDate($order->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);

$orderStoreDate = $block->formatDate(
    $order->getCreatedAt(),
    \IntlDateFormatter::MEDIUM,
    true,
    $block->getTimezoneForStore($order->getStore())
);

/** @var \Temando\Shipping\ViewModel\Order\Location $locationViewModel */
$viewModel = $block->getData('locationViewModel');
/** @var \Temando\Shipping\ViewModel\Order\OrderDetails $orderDetailsViewModel */
$orderDetailsViewModel = $block->getData('orderDetailsViewModel');
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Order & Account Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */ ?>
            <?php
            $confirmationEmailStatusMessage = $order->getEmailSent()
                ? __('The order confirmation email was sent')
                : __('The order confirmation email is not sent');
            ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php if ($block->getNoUseOrderLink()) : ?>
                        <?php echo $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?>
                        (<span><?php echo $block->escapeHtml($confirmationEmailStatusMessage) ?></span>)
                    <?php else : ?>
                        <a href="<?php echo $block->escapeHtml($block->getViewUrl($order->getId())) ?>">
                            <?php echo $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?>
                        </a>
                        <span>(<?php echo $block->escapeHtml($confirmationEmailStatusMessage) ?>)</span>
                    <?php endif; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Order Date')) ?></th>
                        <td><?php echo $block->escapeHtml($orderAdminDate) ?></td>
                    </tr>

                    <?php if ($orderAdminDate != $orderStoreDate) : ?>
                        <tr>
                            <?php // @codingStandardsIgnoreLine ?>
                            <th><?php echo $block->escapeHtml(__('Order Date (%1)', $block->getTimezoneForStore($order->getStore()))) ?></th>
                            <td><?php echo $block->escapeHtml($orderStoreDate) ?></td>
                        </tr>
                    <?php endif;?>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Order Status')) ?></th>
                        <td><span id="order_status"><?php echo $block->escapeHtml($order->getStatusLabel()) ?></span></td>
                    </tr>

                    <?php //echo /* @noEscape */ $block->getChildHtml() ?>

                    <?php if ($block->isSingleStoreMode() == false) : ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Purchased From')) ?></th>
                            <td><?php echo $block->escapeHtml($block->getOrderStoreName(), ['br']) ?></td>
                        </tr>
                    <?php endif; ?>

                    <?php if ($order->getRelationChildId()) : ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Link to the New Order')) ?></th>
                            <td>
                                <a href="<?php echo $block->escapeUrl($block->getViewUrl($order->getRelationChildId())) ?>">
                                    <?php echo $block->escapeHtml($order->getRelationChildRealId()) ?>
                                </a>
                            </td>
                        </tr>
                    <?php endif; ?>

                    <?php if ($order->getRelationParentId()) : ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Link to the Previous Order')) ?></th>
                            <td>
                                <a href="<?php echo $block->escapeUrl($block->getViewUrl($order->getRelationParentId())) ?>">
                                    <?php echo $block->escapeHtml($order->getRelationParentRealId()) ?>
                                </a>
                            </td>
                        </tr>
                    <?php endif; ?>

                    <?php if ($order->getRemoteIp() && $block->shouldDisplayCustomerIp()) : ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Placed from IP')) ?></th>
                            <td>
                                <?php echo $block->escapeHtml($order->getRemoteIp()); ?>
                                <?php if ($order->getXForwardedFor()) : ?>
                                    (<?php echo $block->escapeHtml($order->getXForwardedFor()) ?>)
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endif; ?>

                    <?php if ($order->getGlobalCurrencyCode() != $order->getBaseCurrencyCode()) : ?>
                        <tr>
                            <?php // @codingStandardsIgnoreLine ?>
                            <th><?php echo $block->escapeHtml(__('%1 / %2 rate:', $order->getGlobalCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                            <td><?php echo $block->escapeHtml($order->getBaseToGlobalRate()) ?></td>
                        </tr>
                    <?php endif; ?>

                    <?php if ($order->getBaseCurrencyCode() != $order->getOrderCurrencyCode()) : ?>
                        <tr>
                            <?php // @codingStandardsIgnoreLine ?>
                            <th><?php echo $block->escapeHtml(__('%1 / %2 rate:', $order->getOrderCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                            <td><?php echo $block->escapeHtml($order->getBaseToOrderRate()) ?></td>
                        </tr>
                    <?php endif; ?>

                    <?php $extOrderId = $orderDetailsViewModel->getExtOrderId($order); ?>
                    <?php if ($extOrderId) : ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Magento Shipping Order ID')) ?></th>
                            <td><?php echo $block->escapeHtml($extOrderId) ?></td>
                        </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /* Account Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Account Information')) ?></span>
                <div class="actions">
                    <?php if ($customerUrl = $block->getCustomerViewUrl()) : ?>
                        <a href="<?php echo $block->escapeUrl($block->getCustomerViewUrl()) ?>" target="_blank">
                            <?php echo $block->escapeHtml(__('Edit Customer')) ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Customer Name')) ?></th>
                        <td>
                            <?php if ($customerUrl = $block->getCustomerViewUrl()) : ?>
                                <a href="<?php echo $block->escapeUrl($customerUrl) ?>" target="_blank">
                                    <span><?php echo $block->escapeHtml($order->getCustomerName()) ?></span>
                                </a>
                            <?php else : ?>
                                <?php echo $block->escapeHtml($order->getCustomerName()) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Email')) ?></th>
                        <td><?php echo $block->getChildHtml('order_info_email') ?></td>
                    </tr>
                    <?php if ($groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Customer Group')) ?></th>
                            <td><?php echo $block->escapeHtml($groupName) ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data) : ?>
                        <tr>
                            <th><?php echo $block->escapeHtml($data['label']) ?></th>
                            <td><?php echo $block->escapeHtml($data['value'], ['br']) ?></td>
                        </tr>
                    <?php endforeach;?>
                    <?php echo /* @noEscape */ $block->getChildHtml('extra_customer_info') ?>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Address Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-billing-address">
            <?php /* Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Billing Address')) ?></span>
                <div class="actions"><?php echo /* @noEscape */ $block->getAddressEditLink($order->getBillingAddress()); ?></div>
            </div>
            <address class="admin__page-section-item-content">
                <?php echo /* @noEscape */ $block->getFormattedAddress($order->getBillingAddress()); ?>
            </address>
        </div>

        <?php if (!$order->getIsVirtual()) : ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php
                    /* Shipping Address */
                    $deliveryLocationAddressHtml = $viewModel->getCollectionPointAddressHtml($order);
                ?>

                <?php if (!$deliveryLocationAddressHtml) : ?>
                    <?php // render original shipping address ?>
                    <div class="admin__page-section-item-title">
                        <span class="title"><?php echo $block->escapeHtml(__('Shipping Address')) ?></span>
                        <div class="actions"><?php echo /* @noEscape */ $block->getAddressEditLink($order->getShippingAddress()); ?></div>
                    </div>

                    <address class="admin__page-section-item-content">
                        <?php echo /* @noEscape */ $block->getFormattedAddress($order->getShippingAddress()); ?>
                    </address>
                <?php else : ?>
                    <?php // render delivery point and destination address ?>
                    <div class="admin__page-section-item-title">
                        <span class="title"><?php echo $block->escapeHtml(__('Shipping Address'))  ?></span>
                    </div>

                    <div class="admin__page-section-item-content order-shipping-primary-address">
                        <span class="subtitle"><?php echo $block->escapeHtml(__('Collection Point')) ?></span>
                    </div>
                    <address class="admin__page-section-item-content order-shipping-primary-address">
                        <?php echo /* @noEscape */ $deliveryLocationAddressHtml; ?>
                    </address>

                    <div class="admin__page-section-item-content order-shipping-secondary-address">
                        <span class="subtitle"><?php echo $block->escapeHtml(__('Recipient Address')) ?></span>
                    </div>
                    <address class="admin__page-section-item-content order-shipping-secondary-address">
                        <?php echo /* @noEscape */ $block->getFormattedAddress($order->getShippingAddress()); ?>
                    </address>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</section>
