<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_DependentCustomOption
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
/**
 *
 * @var \Bss\DependentCustomOption\Block\Adminhtml\Product\Edit $block
 */

?>
<?php if ($block->isModuleEnable()): ?>
<?php
	$dependentId = $bssDependOptions = [];
	$product = $block->getProduct();
	if ($product->getId()) {
        foreach ($product->getOptions() as $o) {
            $dependOption = [];
            if ($o->getDependentId()) {
                $dependOption[$o->getDependentId()] = true;
                $dependentId[$o->getDependentId()] = $o->getTitle();
            }
            if (!empty($o->getValues())) {
                foreach ($o->getValues() as $value) {
                    $data =  $value->getData();
                    if (isset($data['dependent_id'])){
                        $dependOption[$data['dependent_id']] = true;
                        $dependentId[$data['dependent_id']] = $value->getTitle();
                    }
                }
            }
            $bssDependOptions[] = $dependOption;
        }
    }
 ?>
<input hidden id="depend-last-increment-id" value="<?= $block->getLastIncrementId() ?>">
<script>
    require(["jquery"], function($) {
    	window.bss_depend_option = <?php /* @escapeNotVerified */ echo json_encode($bssDependOptions, JSON_FORCE_OBJECT) ?>;
        window.bss_depend_id = <?php /* @escapeNotVerified */ echo json_encode($dependentId, JSON_FORCE_OBJECT) ?>;
        $(document).ready(function(){
        	$(document).on('click', '.action-delete', function (event) {
        	    var optionKey = 0;
	        	$(this).parents('tr.data-row').find('.bss-dependent-id').each(function() {
                    optionKey = $(this).attr('option_key');
	        		window.bss_depend_option[$(this).attr('option_key')][$(this).val()] = false;
	        		window.bss_depend_id[$(this).val()] = false;
	        	});
                if ($(this).closest('tr.data-row').find('.check-depend-is-parent-option').length > 0) {
                    var cloneBssDependOption = {};
                    var countLoop = 0;
                    delete window.bss_depend_option[optionKey];
                    Object.keys(window.bss_depend_option).map(function(key) {
                        cloneBssDependOption[countLoop] = window.bss_depend_option[key];
                        countLoop++;
                    });
                    window.bss_depend_option = cloneBssDependOption;
                }

			});
		})
    });
</script>
<?php endif ?>
