<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_Faqs
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category page main block
 *
 * @var $block Bss\Faqs\Block\Adminhtml\Grid\Assign\*
 */
$moduleConfig = $block->getModuleConfig();
?>
<input id="<?php echo $block->getFieldId(); ?>" name="<?php echo $block->getFieldId(); ?>" type="hidden" />
<?php  echo $block->getGridHtml(); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_Faqs/js/assign_grid": {
                "dependence": "<?php echo $block->getDependence(); ?>",
                "fieldId": "<?php echo $block->getFieldId(); ?>",
                "tableId": "<?php echo $block->getTableId(); ?>",
                "sourceId": "<?php echo $block->getSourceId(); ?>",
                "jsObjectName": "<?php echo $block->getBlockGrid()->getJsObjectName(); ?>"
            }
        }
    }
</script>
