<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_CheckoutMsg
 * @author    Extension Team
 * @copyright Copyright (c) 2024 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<?php // @codingStandardsIgnoreFile ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Bss_CheckoutMsg/js/view/model/custom-message": {
                "customMessage": "<?= $block->getCustomMessage(); ?>"
        	}
        }
    }
</script>
