<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */

$actionPosition='actions--right-to-cart';
$breedteValue = (int)$block->getRequest()->getParam('breedte_value');
$hoogteValue = (int)$block->getRequest()->getParam('hoogte_value');

?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Configuration'); ?>

<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart <?= $block->escapeHtml($actionPosition) ?>">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control qty-controls-wrap">
                        <a class="icon-minus qty-minus"></a>
                        <a class="icon-plus qty-plus"></a>
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->escapeHtmlAttr($block->getProductDefaultQty() * 1) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        disabled
                        id="product-addtocart-button">
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Bss_RequiredProduct/js/product/view/validate-product": {}
        }
    }
</script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const breedte = "<?= $breedteValue ?>";
        const hoogte =  "<?= $hoogteValue ?>";

        if (breedte && hoogte) {
            const requiredFields = document.querySelectorAll('.requiredproduct-product-view input[name], .requiredproduct-product-view select[name], .requiredproduct-product-view textarea[name]');

            requiredFields.forEach(field => {
                const label = document.querySelector(`label[for="${field.id}"]`);
                const labelText = label ? label.innerText.trim() : "";
                if (labelText === "Lengte (mm)" || labelText === "Hoogte (mm)") {
                    if (labelText === "Lengte (mm)") {
                        field.value = breedte;
                    }
                    if (labelText === "Hoogte (mm)") {
                        field.value = hoogte;
                    }
                }
            });
        }
    });
</script>


