<?php
$taxRate = $block->getTaxRate();
?>

<style>
    .hidden {
        display: none;
    }
</style>

<div class="prijsoverzicht-box" data-bind="scope: 'priceSummary'">
    <h2>Prijsoverzicht:</h2>
    <ul>
        <li class="show-if-has-discount hidden">
            <span>Normal price:</span>
            <span class="old_price_btw-value" style="float: right;">€ 0</span>
        </li>
        <li class="show-if-has-discount hidden">
            <span>Korting:</span>
            <span class="discount_price_btw-value" style="float: right;">€ 0</span>
        </li>
        <li class="total_excl_btw">
            <span class="show-if-not-has-discount">Prijs excl. BTW:</span>
            <span class="show-if-has-discount hidden">Special price:</span>
            <span class="total_excl_btw-value" style="float: right;">€ 0</span>
        </li>
        <li class="product_btw">
            <span>Btw <?= $taxRate . "%" ?>:</span>
            <span class="product_btw-value" style="float: right;">€ 0</span>
        </li>
    </ul>
</div>

<div class="product-info-price">
    <div class="total_incl_btw">
        <span>Totaal incl. BTW:</span>
        <span class="total_incl_btw-value" style="float: right;">€ 0</span>
    </div>
</div>
