<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_OrderDeliveryDate
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php
    $helper = \Magento\Framework\App\ObjectManager::getInstance()->create('Bss\OrderDeliveryDate\Helper\Data');
?>
<div id="order-messages">
    <?php echo $block->getChildHtml('order_messages') ?>
</div>
<?php
    $check = false;
    $items = $_order->getAllVisibleItems();
    foreach ($items as $item) {
        $productType = $item->getProduct()->getTypeId();
        if ($productType != "downloadable" && $productType != "virtual") {
            $check = true;
            continue;
        }
    }
?>
<!-- start add delivery date -->
<?php if($helper->isEnabled() && $check): ?>
<section class="admin__page-section" style="margin-bottom:0">
    <div class="admin__page-section-item order-delivery-date">
            <div class="admin__page-section-item-title">
                <strong><?php echo __('Leverdatum:') ?></strong>
				<?php if($_order->getShippingArrivalDate()):?>
                            <span><?php echo $helper->formatDate($_order->getShippingArrivalDate());?></span>
                        <?php else:?></span>
                        <?php endif;?>
                <div class="actions">
                    <a href="<?php echo $this->getUrl('orderdeliverydate/order/delivery', ['order_id' => $_order->getId()]); ?>">
                        <?php if($_order->getShippingArrivalDate()):?>
                            <span><?php echo __('Bewerken');?></span>
                        <?php else:?><span><?php echo __('Invoeren');?></span>
                        <?php endif;?>
                    </a>
                </div>
            </div>
          
        </div>
</section>
<?php endif;?>
<!-- end add delivery date -->
<?php echo $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?php /* @escapeNotVerified */ echo $_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?php if ($_order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?php echo $block->getPaymentHtml() ?></div>
                <div class="order-payment-currency"><?php /* @escapeNotVerified */ echo __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                <div class="order-payment-additional">
                    <?php echo $block->getChildHtml('order_payment_additional'); ?>
                    <?php echo $block->getChildHtml('payment_additional_info'); ?>
                </div>
            </div>
        </div>
        <?php echo $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>


<?php echo $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Items Ordered') ?></span>
    </div>
    <?php echo $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Notes for this Order') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Order Totals') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?php echo $block->getChildHtml('popup_window');?>

<script type="text/x-magento-init">
    {
        "*": {
            "Bss_OrderDeliveryDate/js/order/view/tab/info": {
            }
        }
    }
</script>
