<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
	$products = $this->_ajaxLoad();
	$config   = $this->_getConfig();
} else {
	$config   = $this->getData('config');
	$products = $this->getData('products');
}
$_helper         = $this->helper('Magento\Catalog\Helper\Output');
$_config         = $this->helper('Sm\Market\Helper\Data');
$homeStyle       = $_config->getThemeLayout('home_style');
$viewMode        = 'grid';
$image           = 'category_page_grid';
$showDescription = false;
$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore   = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark        = $type_loadmore ? ' ltabs-mark ' : '';

$nb_type_show = $config['type_show'];

$nb_rows = 7;
$i       = 0;
$count   = count($products);
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
?>
<div class="<?php /* @escapeNotVerified */
echo $viewMode; ?> products-<?php /* @escapeNotVerified */
echo $viewMode; ?>">
        <?php $iterator = 1; ?>
    <div class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
		<?php foreach ($products as $_product):

			?>
			<?php /* @escapeNotVerified */
			echo ($iterator++ == 1) ? '<div class="item product product-item ' . $cls_mark . '">' : '</div><div class="item product product-item ' . $cls_mark . '">' ?>
            <div class="product-item-info" data-container="product-grid">
					<div class="item-inner">
						<?php
						$productImage = $block->getImage($_product, $image);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						?>

						<?php // Product Image
						?>
                        <div class="box-image">
							<a href="<?php /* @escapeNotVerified */
							echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>

                            <!--LABEL PRODUCT-->
							<?php
							$orgprice             = $_product->getPrice();
							$specialprice         = $_product->getSpecialPrice();
							$specialPriceFromDate = $_product->getSpecialFromDate();
							$specialPriceToDate   = $_product->getSpecialToDate();

							$today = time();

							if ($specialprice && $_config->getAdvanced('show_salelabel')) {
								if ($specialPriceFromDate !== null && $today >= strtotime($specialPriceFromDate)) {
									if ($specialPriceToDate === null || $today <= strtotime($specialPriceToDate)) {
										if ($specialprice < $orgprice) {
											$save_percent = 100 - round(($specialprice / $orgprice) * 100);
											?>
											<div class="label-product label-sale">
												<span class="sale-product-icon">
													<?php echo '-' . $save_percent . '%'; ?>
												</span>
											</div>
											<?php
										}
									}
								}
							}
							?>

							<?php
							$now      = date("Y-m-d");
							$newsFrom = $_product->getNewsFromDate();
							$newsTo   = $_product->getNewsToDate();

							if (($newsTo !== null || $newsFrom !== null) && $_config->getAdvanced('show_newlabel')) {
								$newsFromSubstring = $newsFrom !== null ? substr($newsFrom, 0, 10) : null;
								$newsToSubstring   = $newsTo !== null ? substr($newsTo, 0, 10) : null;

								if (
									($newsToSubstring !== '' && $newsFromSubstring !== '' && $now >= $newsFromSubstring && $now <= $newsToSubstring) ||
									($newsToSubstring === '' && $now >= $newsFromSubstring) ||
									($newsFromSubstring === '' && $now <= $newsToSubstring)
								) { ?>
									<div class="label-product label-new">
										<span class="new-product-icon"><?php echo __('New'); ?></span>
									</div>
								<?php }
							}
							?>
                            <!--END LABEL PRODUCT-->

							<?php if ($homeStyle == 'home-16' || $homeStyle == 'home-17' || $homeStyle == 'home-18' || $homeStyle == 'home-19' || $homeStyle == 'home-20') { ?>
                                <div class="button-action">
									<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
											echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
												<span><?php /* @escapeNotVerified */
													echo __('Add to Wish List') ?></span>
											</a>
										<?php endif; ?>
									<?php } ?>

									<?php if ($_config->getAdvanced('show_compare_button')) { ?>
										<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                        <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
										echo $compareHelper->getPostDataParams($_product); ?>' role="button">
											<span><?php /* @escapeNotVerified */
												echo __('Add to Compare') ?></span>
										</a>
									<?php } ?>
								</div>
							<?php } ?>
						</div>
						
						
<div class="product details product-item-details box-info">							
							<?php
$productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
$len = strlen($productName);
?>
<h2 class="product name product-item-name product-name">
<a class="product-item-link" href="<?php echo /* @escapeNotVerified */ $_product->getProductUrl() ?>">
    <?php echo substr($productName,0,55); ?>
    <?php if($len > 55) echo '...'; ?>
</a></h2>
							
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
							<?php /* @escapeNotVerified */
							echo $block->getProductPrice($_product) ?>
							<?php echo $block->getProductDetailsHtml($_product); ?>

							<?php
							if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
								$specialToDate = $_product->getSpecialToDate();
								?>
                                <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
								<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
							</div>
							<?php } ?>

														<div class="bekijken">
									<a href="<?php /* @escapeNotVerified */	echo $_product->getProductUrl() ?>"><span>Bekijken</span></a>
									</div>
						</div>
					</div>
                </div>
			<?php echo ($iterator == count($products) + 1) ? '</div>' : '' ?>
		<?php endforeach; ?>
        </div>
    </div>
