<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Setup;

use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;
use Magento\Framework\Setup\UninstallInterface;

/**
 * For uninstallation
 * Class Uninstall
 */
class Uninstall implements UninstallInterface
{

    /**
     * Uninstall Script
     *
     * @param SchemaSetupInterface   $setup
     * @param ModuleContextInterface $context
     * @return void
     */
    public function uninstall(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
        $setup->startSetup();

        // remove vat_validation table
        $setup->getConnection()->dropTable($setup->getTable('vat_validation'));

        // remove additional columns on quote, order and address entity tables
        $connection = $setup->getConnection();
        $quoteAddressTable = $connection->getTableName($setup->getTable('quote_address'));
        $orderAddressTable = $connection->getTableName($setup->getTable('sales_order_address'));
        $customerAddressTable = $setup->getTable('customer_address_entity');

        $connection->dropColumn($quoteAddressTable, 'vat_trader_name');
        $connection->dropColumn($quoteAddressTable, 'vat_trader_address');

        $connection->dropColumn($orderAddressTable, 'vat_trader_name');
        $connection->dropColumn($orderAddressTable, 'vat_trader_address');

        $connection->dropColumn($customerAddressTable, 'vat_trader_name');
        $connection->dropColumn($customerAddressTable, 'vat_trader_address');

        $setup->endSetup();
    }
}
