<?php
/**
 * @var \Fooman\PdfCustomiser\Block\Pdf\OrderShipment $block
 *
 * Note on the use of @noEscape throughout this template
 * html output is allowed by design to allow users to customise their pdfs
 */
?>
<?php $order = $block->getOrder() ?>
<?php $design = $block->getDesign() ?>

<table width="100%" border="0" cellpadding="8" cellspacing="0">
    <tr>
        <?php if ($block->isLogoOnRight()): ?>
            <td align="top"
                width="50%"
                height="30mm"
                style="font-weight:bold;font-size:<?= /* @noEscape */ $block->getFontsize('large') ?>"
            ><?= $block->escapeHtml($block->getTitle()) ?>
                <?= /* @noEscape */ $block->getBarcodeBlock('shipment', 'L', false) ?></td>
            <td valign="top">&nbsp;<?= /* @noEscape */ $block->getLogoBlock() ?></td>
        <?php else: ?>
            <td width="50%"
                valign="top"><?= /* @noEscape */ $block->getLogoBlock() ?></td>
            <td valign="top"
                height="30mm"
                style="font-weight:bold;font-size:<?= /* @noEscape */ $block->getFontsize('large') ?>"
            ><?= $block->escapeHtml($block->getTitle()) ?>
                <?= /* @noEscape */ $block->getBarcodeBlock('shipment', 'L') ?></td>
        <?php endif; ?>
    </tr>
    <tr>
        <td valign="top" width="50%"><?= $block->escapeHtml(__('Shipment #')) ?>:
            <?= $block->escapeHtml($order->getIncrementId()) ?><br/>
            <?= $block->escapeHtml(__('Ship Date')) ?>:
            <?= /* @noEscape */ $block->getFormattedDate($order->getCreatedAt()) ?><br/>
            <?php if ($block->showOrderIncrementId()): ?>
                <?= $block->escapeHtml(__('Order #') . ': ' . $order->getIncrementId()) ?><br/>
            <?php endif; ?>
            <?= $block->escapeHtml(__('Order Date')) ?>: <?= /* @noEscape */ $block->getFormattedDate($order->getCreatedAt()) ?><br/>

            <?php $customText = $block->getCustomText() ?>
<?php if ($customText) : ?>
    <table width="80%" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td><?php echo $customText ?></td>
        </tr>
    </table>
<?php endif; ?>
<?= /* @noEscape */ $block->getCommentsBlock() ?> 
        </td>
        <td valign="top">
		Geerdink Bouwmaterialen B.V.<br/>
H.o.d.n. Glasdiscount.nl<br/>
Hoofdweg 60<br/>
7371 AJ Loenen GLD<br/>
tel; 055-843 42 02<br/>
<br/>
<strong>Btw nummer:</strong>  8565.12.187.B01<br/>
<strong>Rek nr:</strong> NL20 RABO 0306 0701 97 t.n.v. <br/>
Geerdink Bouwmaterialen B.V.<br/>
<strong>KvK nummer:</strong> 66359953<br/>
<?php echo $block->getOwnerAddress() ?><?php if ($order->getShipping_arrival_date()) : ?><?php echo date('d M Y', strtotime($order->getShipping_arrival_date())); ?><br/><?php endif; ?></td>
    </tr>
    <tr>
        <?php if ($block->shouldDisplayBothAddresses()): ?>
        <!--Example with indentation of address, adjust the percentages to adjust the left-right positioning
            <td valign="top" colspan="2">
                <table>
                    <tr>
                        <td width="5%"></td>
                        <td width="45%"><?= $block->escapeHtml(__('Sold to:')) ?>
                        <br/><?= /* @noEscape */ $block->getBillingAddress() ?></td>
                        <td width="5%"></td>
                        <td width="45%"><?= $block->escapeHtml(__('Ship to:')) ?>
                        <br/><?= /* @noEscape */ $block->getShippingAddress() ?></td>
                    </tr>
                </table>
            </td>-->
        <td valign="top"
            width="50%"
            style="<?= /* @noEscape */ $block->getDesign()->getHeaderStyle(true, true)?>"
        ><?= $block->escapeHtml(__('Sold to:')) ?></td>
        <td valign="top"
            style="<?= /* @noEscape */ $block->getDesign()->getHeaderStyle(true, true)?>"
        ><?php if (!$order->getIsVirtual()):
            ?><?= $block->escapeHtml(__('Ship to:')) ?><?php
            endif; ?></td>
    </tr>
    <tr>
        <td valign="top"
            style="<?= /* @noEscape */ $block->getDesign()->getCellStyle(true, true, true, false)?>"
        ><?= /* @noEscape */ $block->getBillingAddress() ?></td>
        <td valign="top"
            style="<?= /* @noEscape */ $block->getDesign()->getCellStyle(true, true, false, true)?>"
        ><?php if (!$order->getIsVirtual()):
            ?><?= /* @noEscape */ $block->getShippingAddress() ?><?php
            endif; ?></td>
        <?php elseif ($block->shouldDisplayShippingAddress()): ?>
            <td valign="top"
                colspan="2"
                style="<?= /* @noEscape */ $block->getDesign()->getHeaderStyle(true, true)?>"></td>
        </tr>
        <tr>
            <td valign="top"
                colspan="2"
                style="<?= /* @noEscape */ $block->getDesign()->getCellStyle(true, true, true, true)?>"
            ><?= /* @noEscape */ $block->getShippingAddress() ?></td>
        <?php elseif ($block->shouldDisplayBillingAddress()): ?>
            <td valign="top"
                colspan="2"
                style="<?= /* @noEscape */ $block->getDesign()->getHeaderStyle(true, true)?>"></td>
        </tr>
        <tr>
            <td valign="top"
                colspan="2"
                style="<?= /* @noEscape */ $block->getDesign()->getCellStyle(true, true, true, true)?>"
            ><?= /* @noEscape */ $block->getBillingAddress() ?></td>
        <?php endif; ?>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    <?php if ($order->getIsVirtual()): ?>
        <tr>
            <td valign="top"
                colspan="2"
                style="<?= /* @noEscape */ $block->getDesign()->getHeaderStyle(true, true)?>"
            ><strong><?= $block->escapeHtml(__('Payment Method')) ?></strong></td>
        </tr>
        <tr>
            <td valign="top"
                colspan="2"
                style="<?= /* @noEscape */ $block->getDesign()->getCellStyle(true, true, true, true)?>"
            ><?= /* @noEscape */ $block->getPaymentBlock() ?></td>
        </tr>
    <?php else: ?>
        <tr>
            <td valign="top"
                width="50%"
                style="<?= /* @noEscape */ $block->getDesign()->getHeaderStyle(true, true)?>"
            ><strong><?= $block->escapeHtml(__('Payment Method')) ?></strong></td>
            <td valign="top"
                style="<?= /* @noEscape */ $block->getDesign()->getHeaderStyle(true, true)?>"
            ><strong><?= $block->escapeHtml(__('Shipping Method')) ?></strong></td>
        </tr>
        <tr>
            <td valign="top"
                width="50%"
                style="<?= /* @noEscape */ $block->getDesign()->getCellStyle(true, true, true, false)?>"
            ><?= /* @noEscape */ $block->getPaymentBlock() ?></td>
            <td valign="top"
                style="<?= /* @noEscape */ $block->getDesign()->getCellStyle(true, true, false, true)?>"
            ><?= /* @noEscape */ $block->getShippingBlock() ?></td>
        </tr>
    <?php endif; ?>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
</table>

<?= /* @noEscape */ $block->getItemsBlock($design->getItemStyling()) ?>

<?= /* @noEscape */ $block->getGiftmessageBlock()?>

<?php $groupText = $block->getGroupText($order->getCustomerGroupId()) ?>
<?php if ($groupText): ?>
    <br/>
    <table width="100%" border="0" cellpadding="2" cellspacing="0">
        <tr>
            <td colspan="2"> <?= /* @noEscape */ $groupText ?></td>
        </tr>
    </table>
<?php endif; ?>
