<?php /** @var $block \Woom\CmsTree\Block\Adminhtml\Page\Edit */ ?>
<div data-id="information-dialog-cms" class="messages" style="display: none;">
    <div class="message message-notice">
        <div><?php /* @escapeNotVerified */ echo __('This operation can take a long time'); ?></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "pageForm": {"refreshUrl": "<?php /* @escapeNotVerified */ echo $block->getRefreshPathUrl() ?>"}
        }
    }
</script>
