<?php if ($weight = $block->getTotalWeight()):?>
<div class="cart-totals total-weight">
    <table class="data table totals">
        <tbody>
        <tr class="grand totals excl">
            <th class="mark" scope="row">
                <strong><?= __("Total Weight")?></strong>
            </th>
            <td class="amount">
                <strong><span class="price"><?= $weight?></span></strong>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<?php endif;?>
