<!-- Mopinion Pastea.se  start -->
<script type="text/javascript">(function(){var id="<?php echo $block->getConfig(\Mopinion\FeedbackSurvey\Helper\Data::XML_PATH_MOPINIONKEY); ?>";var js=document.createElement("script");js.setAttribute("type","text/javascript");js.setAttribute("src","//deploy.mopinion.com/js/pastease.js");js.async=true;document.getElementsByTagName("head")[0].appendChild(js);var t=setInterval(function(){try{new Pastease.load(id);clearInterval(t)}catch(e){}},50)})();</script>
<!-- Mopinion Pastea.se end -->
