<?php
/**
 * MageDelight
 * Copyright (C) 2023 Magedelight <info@magedelight.com>
 *
 * @category MageDelight
 * @package Magedelight_Megamenu
 * @copyright Copyright (c) 2023 Magedelight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

$selectedOptions = $block->getAnimationOption();
$optionGroups = $block->getOptions();
?>
    <select class="admin__control-select animationFields">
        <option value="none"><?php echo __('None') ?></option>
    <?php
    foreach ($optionGroups as $optionGroup) {
        ?>
        <optgroup label="<?= /* @noEscape */ $optionGroup['label']; ?>">
            <?php
            $optionValues = $optionGroup['value'];
            foreach ($optionValues as $optionValue) {
                $selected = '';
                if ($selectedOptions == $optionValue['value']) {
                    $selected = 'selected';
                }
                ?>
                <option <?= /* @noEscape */ $selected; ?> value="<?= /* @noEscape */ $optionValue['label']; ?>">
                    <?= /* @noEscape */ $optionValue['value']; ?></option>
                <?php
            }
            ?>
        </optgroup>
        <?php
    }
    ?>
    </select>