<?php
/**
 * MageDelight
 * Copyright (C) 2023 Magedelight <info@magedelight.com>
 *
 * @category MageDelight
 * @package Magedelight_Megamenu
 * @copyright Copyright (c) 2023 Magedelight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$menu_id = $block->getCurrentMenuId();
$menu = $block->getCurrentMenu();
$animationsFields = $block->animationSelect();
$megamenutype = $menu->getMenuType();
$menuAlignment = $menu->getMenuAlignment();
$depthLevel = '';
if ($megamenutype == '2') {
    $depthLevel = '1';
} elseif ($megamenutype == '1') {
    $depthLevel = '10';
}

?>

<script type="text/javascript">
    var menuDepthLevel = '<?= /* @noEscape */ $depthLevel; ?>';
    var animationsFields = '<?= /* @noEscape */ $animationsFields; ?>';
    function htmlDecode(input){
        var e = document.createElement('textarea');
        e.innerHTML = input;
        // handle case of empty input
        return e.childNodes.length === 0 ? "" : e.childNodes[0].nodeValue;
    }
<?php
if ($menu_id) {
    ?>
        var menuType = '<?= /* @noEscape */ $menu->getMenuType(); ?>';
        var menuStaticsBlock = '<?= /* @noEscape */ trim(preg_replace('/\s\s+/', ' ', $block->escapeHtml($block->getStaticBlocks()))); ?>';
        menuStaticsBlock = htmlDecode(menuStaticsBlock.replace(/(\r\n|\n|\r)/gm, ""));
        var menuCategorySelectStaticsBlock = '<?= /* @noEscape */ trim(preg_replace('/\s\s+/', ' ', $block->escapeHtml($block->getStaticBlocks('', '', true)))); ?>';
        menuCategorySelectStaticsBlock = htmlDecode(menuCategorySelectStaticsBlock.replace(/(\r\n|\n|\r)/gm, ""));
        var menuTypes = '<?= /* @noEscape */ $block->getMenuLabels(); ?>';
        var menuDesignType = '<?= /* @noEscape */ $menu->getMenuDesignType(); ?>';
    <?php
}
?>
    require([
        'jquery',
        'jquery/ui',
        'Magento_Ui/js/modal/confirm'
    ], function ($, ui, confirmation) {
        $(document).ready(function () {
            $("#tabbed").tabs();
            $('#delete').click(function () {
                var url = $(this).attr('data-url');
                confirmation({
                    title: 'Delete Menu',
                    content: 'Are You sure, You want to delete this Menu.',
                    actions: {
                        confirm: function () {
                            setLocation(url)
                        }
                    }
                });
            });

            var menuDesignType = $("#menu_design_type").val();
            if(menuDesignType == 'horizontal') {
                $("#menu_alignment_control").css("display", "block");
            } else {
                $("#menu_alignment_control").css("display", "none");
            }
            if(menuDesignType == 'all-category'){
                $("#menu_alignment_control").css("display", "none");
                $("#is_sticky_control").css("display", "none");
            }
            $('#menu_design_type').change(function () {
                var val = $(this).val();
                if(val == 'horizontal') {
                    $("#menu_alignment_control").css("display", "block");
                } if(val == 'all-category'){
                    $("#menu_alignment_control").css("display", "none");
                    $("#is_sticky_control").css("display", "none");
                }
                else {
                    $("#menu_alignment_control").css("display", "none");
                }
            });

        });
    });
</script>

<div class="page-main-actions">
    <div class="page-actions">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <button id="back" onclick="location.href = '<?= /* @noEscape */ $block->getUrl('*/*/'); ?>'" class="action- scalable back" data-ui-id="back-button" type="button" title="<?= /* @noEscape */  __('Back'); ?>"><span><?= /* @noEscape */ __('Back'); ?></span> </button>
                <button id="delete" data-url="<?= /* @noEscape */ $block->getUrl('*/*/delete', ['menu_id' => $menu_id]); ?>" class="action- scalable delete" data-ui-id="delete-button" type="button" title="Delete Menu"><span><?= /* @noEscape */  __('Delete Menu'); ?></span> </button>
                <button id="reset" class="action- scalable reset" data-ui-id="reset-button" onclick="location.reload();" type="button" title="Reset"><span><?= /* @noEscape */  __('Reset Menu'); ?></span> </button>
                <button id="save_and_continue" class="action- scalable save ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only megamenu-save-continue" type="button" title="Save and Continue Edit"><span><?= /* @noEscape */  __('Save and Continue Edit'); ?></span> </button>
                <button id="save" class="action- scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only megamenu-save" type="button" title="Save Menu"><span><?= /* @noEscape */ __('Save Menu'); ?></span> </button>
            </div>
        </div>
    </div>
</div>

<form action="<?= /* @noEscape */ $block->getFormAction(); ?>" method="POST" id="megamenu_form" enctype="multipart/form-data" >
    <div id="tabbed">
        <ul class="tabs-horiz ">
            <li class="ui-state-default ui-corner-top" >
                <a href="#menu_content" title="Menu Main Content" class="ui-tabs-anchor">
                    <span>Menu</span>
                </a>
            </li>
            <?php
            if ($menu_id) {
                ?>
                <li class="ui-state-default ui-corner-top">
                    <a href="#menu_item_content" title="Menu Item Main Content" class="ui-tabs-anchor">
                        <span> Menu Items</span>
                    </a>
                </li>
                <?php
            }
            ?>
        </ul>

        <input type="hidden" name="form_key" value='<?= /* @noEscape */ $block->getFormKey(); ?>' />
        <input type="hidden" name="menu_id" value='<?= /* @noEscape */ $menu_id; ?>' />
        <input type="hidden" name="totalMenus" class="totalMenus" value="" />
        <input type="hidden" id="menu_back" name="back" value='0' />
        <div class="admin__fieldset-wrapper-content" id="menu_content">
            <fieldset class="admin__fieldset">
                <?php
                $status = $menu->getIsActive();
                if ($status == '1') {
                    $enable_checked = 'checked';
                } else {
                    $enable_checked = '';
                    $status == '0';
                }
                ?>
                <div class="admin__field">
                    <label class="admin__field-label" for="is_active">
                        <span><?= /* @noEscape */ __('Enable Menu'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <div data-role="switcher" class="admin__actions-switch">
                            <input type="checkbox" <?= /* @noEscape */  $enable_checked; ?>
                                   class="admin__actions-switch-checkbox" id="is_active" name="is_active"
                                   value="<?= /* @noEscape */ $status; ?>">
                            <label class="admin__actions-switch-label" for="is_active">
                                <span class="admin__actions-switch-text  is_active_label" data-text-on="Yes"
                                      data-text-off="No"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="admin__field _required">
                    <label class="admin__field-label" for="menu_name">
                        <span><?= /* @noEscape */ __('Menu Title'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" class="admin__control-text required-entry" id="menu_name"
                               name="menu_name" value="<?= /* @noEscape */ $menu->getMenuName(); ?>">
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label" for="menu_style">
                        <span><?= /* @noEscape */ __('Menu Style'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <textarea id="menu_style" class="admin__control-textarea" name="menu_style" cols="15" rows="2" placeholder=""><?= /* @noEscape */ $menu->getMenuStyle(); ?></textarea>
                        <div class="admin__field-note">
                            <span><?= /* @noEscape */  __('Only applicable for Megamenu. You can add custom css here'); ?></span>
                        </div>
                    </div>
                </div>
                <div class="admin__field _required">
                    <label class="admin__field-label" for="customer_groups">
                        <span><?= /* @noEscape */ __('Customer Groups'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <?= /* @noEscape */ $block->getCustomerGroupHtml(); ?>
                    </div>
                </div>
                <?php
                $enableSelected = '';
                $disableSelected = '';
                $disabledoption = '';
                $status = intval($menu->getMenuType());

                if ($status != 2) {
                    $enableSelected = 'selected';
                } else {
                    $disableSelected = 'selected';
                }
                if ($menu_id) {
                    $disabledoption = 'disabled';
                }
                ?>
                <div class="admin__field">
                    <label class="admin__field-label" for="menu_type">
                        <span><?= /* @noEscape */ __('Menu Type'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select class="admin__control-select" <?= /* @noEscape */ $disabledoption; ?> name="menu_type" id="menu_type">
                            <option data-title="NORMAL MENU" <?= /* @noEscape */ $enableSelected; ?> value="1"><?= /* @noEscape */ __('NORMAL MENU'); ?></option>
                            <option data-title="MEGA MENU" <?= /* @noEscape */ $disableSelected; ?> value="2"><?= /* @noEscape */ __('MEGA MENU'); ?></option>
                        </select>
                    </div>
                </div>
                <?php
                $menuDesignType = $menu->getMenuDesignType();
                ?>
                <div class="admin__field">
                    <label class="admin__field-label" for="menu_type">
                        <span><?= /* @noEscape */ __('Menu Design Type'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select class="admin__control-select" <?= /* @noEscape */ $disabledoption; ?> name="menu_design_type" id="menu_design_type">
                            <option data-title="Horizontal Menu" <?= /* @noEscape */ ($menuDesignType == 'horizontal') ? 'selected' : ''; ?> value="horizontal"><?= /* @noEscape */ __('Horizontal Menu - Horizontal Category'); ?></option>
                            <option data-title="Horizontal Vertical Menu" <?= /* @noEscape */ ($menuDesignType == 'horizontal-vertical') ? 'selected' : ''; ?> value="horizontal-vertical"><?= /* @noEscape */ __('Horizontal Menu - Vertical Category'); ?></option>
                            <option data-title="Vertical Left" <?= /* @noEscape */ ($menuDesignType == 'vertical-left') ? 'selected' : ''; ?> value="vertical-left"><?= /* @noEscape */ __('Vertical Left Menu'); ?></option>
                            <option data-title="Vertical Right" <?= /* @noEscape */ ($menuDesignType == 'vertical-right') ? 'selected' : ''; ?> value="vertical-right"><?= /* @noEscape */__('Vertical Right Menu'); ?></option>
                            <option data-title="DrillDown Menu" <?= /* @noEscape */ ($menuDesignType == 'drillDown') ? 'selected' : ''; ?> value="drillDown"><?= /* @noEscape */ __('Drill Down Menu'); ?></option>
                            <option data-title="All Category Menu" <?= /* @noEscape */ ($menuDesignType == 'all-category') ? 'selected' : ''; ?> value="all-category"><?= /* @noEscape */ __('All Category Menu'); ?></option>
                            <option data-title="Amazon Menu" <?= /* @noEscape */ ($menuDesignType == 'amazon-menu') ? 'selected' : ''; ?> value="amazon-menu"><?= /* @noEscape */ __('Amazon Menu'); ?></option>
                        </select>
                    </div>
                </div>
                <?php
                    $showVerticalMenuOn = $menu->getShowVerticalMenuOn()
                ?>
                <div class="admin__field" id="show_vertical_menu_on">
                    <label class="admin__field-label" for="show_vertical_menu_on">
                        <span><?= /* @noEscape */ __('Show Menu On'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select class="admin__control-select" name="show_vertical_menu_on" id="show_vertical_menu_on">
                            <option data-title="Click" <?= /* @noEscape */ ($showVerticalMenuOn == 'click') ? 'selected' : ''; ?> value="click"><?= /* @noEscape */ __('Click'); ?></option>
                            <option data-title="Hover" <?= /* @noEscape */ ($showVerticalMenuOn == 'hover') ? 'selected' : ''; ?> value="hover"><?= /* @noEscape */ __('Hover'); ?></option>
                        </select>
                    </div>
                </div>
                <?php
                    $displayPosition = $menu->getDisplayPosition()
                ?>
                <div class="admin__field" id="display_position">
                    <label class="admin__field-label" for="display_position">
                        <span><?= /* @noEscape */ __('Display Position'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select class="admin__control-select" name="display_position" id="display_position">
                            <option data-title="Left" <?= /* @noEscape */ ($displayPosition == 'left') ? 'selected' : ''; ?> value="left"><?= /* @noEscape */ __('Left'); ?></option>
                            <option data-title="Right" <?= /* @noEscape */ ($displayPosition == 'right') ? 'selected' : ''; ?> value="right"><?= /* @noEscape */ __('Right'); ?></option>
                            <option data-title="Center" <?= /* @noEscape */ ($displayPosition == 'center') ? 'selected' : ''; ?> value="center"><?= /* @noEscape */ __('Center'); ?></option>
                        </select>
                    </div>
                </div>
                <?php
                    $displayOverlay = $menu->getDisplayOverlay()
                ?>
                <div class="admin__field" id="display_overlay">
                    <label class="admin__field-label" for="display_overlay">
                        <span><?= /* @noEscape */ __('Display Overlay'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select class="admin__control-select" name="display_overlay" id="display_overlay">
                            <option data-title="0" <?= /* @noEscape */ ($displayOverlay == '0') ? 'selected' : ''; ?> value="0"><?= /* @noEscape */ __('No'); ?></option>
                            <option data-title="1" <?= /* @noEscape */ ($displayOverlay == '1') ? 'selected' : ''; ?> value="1"><?= /* @noEscape */ __('Yes'); ?></option>
                        </select>
                    </div>
                </div>
                <div class="admin__field _required" id="vertical_menu_title">
                    <label class="admin__field-label" for="vertical_menu_title">
                        <span><?= /* @noEscape */ __('Menu Title To Display'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" class="admin__control-text required-entry" id="vertical_menu_title"
                               name="vertical_menu_title" value="<?= /* @noEscape */ ( $menu->getVerticalMenuTitle() ) ? $menu->getVerticalMenuTitle() : __('All Category Menu'); ?>">
                    </div>
                </div>
                <?php
                /*
                $showCategoryIcon = $menu->getShowCategoryIconWithMenu();
                ?>
                <div class="admin__field" id="show_category_icon_with_menu">
                    <label class="admin__field-label" for="show_category_icon_with_menu">
                        <span><?=  __('Show Category Icon With Menu'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select class="admin__control-select" name="show_category_icon_with_menu" id="show_category_icon_with_menu">
                            <option data-title="No" <?=  ($showCategoryIcon == '0') ? 'selected' : ''; ?> value="0"><?= __('No'); ?></option>
                            <option data-title="Yes" <?= ($showCategoryIcon == '1') ? 'selected' : ''; ?> value="1"><?= __('Yes'); ?></option>
                        </select>
                    </div>
                </div> */
                ?>
                <?php
                $showCategoryCount = $menu->getShowCategoryCount();
                ?>
                <div class="admin__field" id="show_category_count">
                    <label class="admin__field-label" for="show_category_count">
                        <span><?= /* @noEscape */ __('Show Category Count'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select class="admin__control-select" name="show_category_count" id="show_category_count">
                            <option data-title="No" <?= /* @noEscape */ ($showCategoryCount == '0') ? 'selected' : ''; ?> value="0"><?= /* @noEscape */ __('No'); ?></option>
                            <option data-title="Yes" <?= /* @noEscape */ ($showCategoryCount == '1') ? 'selected' : ''; ?> value="1"><?= /* @noEscape */ __('Yes'); ?></option>
                        </select>
                    </div>
                </div>
                <?php
                $showViewMore = $menu->getShowViewMore();
                ?>
                <div class="admin__field <?php echo $showViewMore; ?>" id="show_view_more">
                    <label class="admin__field-label" for="show_view_more">
                        <span><?= /* @noEscape */ __('Show View More'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select class="admin__control-select" name="show_view_more" id="show_view_more">
                            <option data-title="No" <?= /* @noEscape */ ($showViewMore == '0') ? 'selected' : ''; ?> value="0"><?= /* @noEscape */ __('No'); ?></option>
                            <option data-title="Yes" <?= /* @noEscape */ ($showViewMore == '1') ? 'selected' : ''; ?> value="1"><?= /* @noEscape */ __('Yes'); ?></option>
                        </select>
                    </div>
                </div>
                <?php
                $hideNoOfSubCategoryToShow = '';
                if ($menu->getShowViewMore() == 0) {
                     $hideNoOfSubCategoryToShow = 'style="display:none;"';
                } ?>
                <div class="admin__field" id="no_of_sub_category_to_show" <?= $hideNoOfSubCategoryToShow ?>>
                    <label class="admin__field-label" for="no_of_sub_category_to_show">
                        <span><?= /* @noEscape */ __('Show View More after Items'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" class="admin__control-text" id="no_of_sub_category_to_show"
                               name="no_of_sub_category_to_show" value="<?= /* @noEscape */  $menu->getNoOfSubCategoryToShow() ? $menu->getNoOfSubCategoryToShow() : 7 ?>">
                    </div>
                </div>
                <div class="admin__field" id="menu_alignment_control" style="display: none;">
                    <label class="admin__field-label" for="menu_alignment">
                        <span><?= /* @noEscape */ __('Menu Alignment'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select class="admin__control-select" name="menu_alignment" id="menu_alignment">
                            <option data-title="Center" <?= /* @noEscape */ ($menuAlignment == 'center') ? 'selected' : ''; ?> value="center"><?= /* @noEscape */ __('Center'); ?></option>
                            <option data-title="Left" <?= /* @noEscape */ ($menuAlignment == 'left') ? 'selected' : ''; ?> value="left"><?= /* @noEscape */ __('Left'); ?></option>
                            <option data-title="Right" <?= /* @noEscape */ ($menuAlignment == 'right') ? 'selected' : ''; ?> value="right"><?= /* @noEscape */__('Right'); ?></option>
                        </select>
                    </div>
                </div>

                <?php
                if ($menu_id) {
                    $megamenutype = $menu->getMenuType();
                    if ($megamenutype == '2') {
                        $isSticky = $menu->getIsSticky();
                        ?>
                        <div class="admin__field" id="is_sticky_control">
                            <label class="admin__field-label" for="is_sticky">
                                <span><?= /* @noEscape */ __('Is Sticky'); ?></span>
                            </label>
                            <div class="admin__field-control">
                                <select class="admin__control-select" name="is_sticky" id="is_sticky">
                                    <option data-title="DISABLED" <?= /* @noEscape */ ($isSticky == '2') ? 'selected' : ''; ?> value="2"><?= /* @noEscape */ __('DISABLED'); ?></option>
                                    <option data-title="ENABLED" <?= /* @noEscape */ ($isSticky == '1') ? 'selected' : ''; ?> value="1"><?= /* @noEscape */ __('ENABLED'); ?></option>
                                </select>
                            </div>
                        </div>
                        <?php
                    }
                }
                ?>
                <div class="admin__field _required">
                    <label class="admin__field-label" for="store_id">
                        <span><?= /* @noEscape */ __('Store View'); ?></span>
                    </label>
                    <div class="admin__field-control">
                        <?php echo $block->getStoreHtml(); ?>
                    </div>
                </div>
                <?php
                if ($menu_id) {
                    $megamenutype = $menu->getMenuType();
                    if ($megamenutype == '2') {
                        ?>
                        <div class="admin__field">
                            <label class="admin__field-label">
                                <span><?= /* @noEscape */ __('Shortcode'); ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input type="text" style="width:715px" class="admin__control-text" value='{{block class="Magedelight\Megamenu\Block\ShortcodeMenu" template="Magedelight_Megamenu::menu/shortcode.phtml" menuid="<?php echo $menu->getMenuId(); ?>"}}' readonly="readonly" />
                                <div class="admin__field-note">
                                    <span><?= /* @noEscape */ __('(Paste this code in your CMS page or static blocks)'); ?></span>
                                </div>
                            </div>
                        </div>
                        <?php
                    }
                }
                ?>
            </fieldset>
        </div>
        <?php
        if ($menu_id) {
            ?>
            <div class="menuitems_block" id="menu_item_content">
                <div class="col-m-3">
                    <div id="magedelight_menu_view_tabs" data-role="container" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
                        <div data-ui-id="sales-order-tabs-title" data-role="title" class="admin__page-nav-title">
                            <strong><?= /* @noEscape */ __('Menu Options'); ?></strong>
                            <span class="admin__page-nav-title-messages" data-role="title-messages"></span>
                        </div>
                        <div>
                            <?php
                            $megamenutype = $menu->getMenuType();
                            $hideBlockInMenuType = ['all-category', 'amazon-menu'];
                            if ($megamenutype != '1' && !in_array($menu->getMenuDesignType(), $hideBlockInMenuType)) {
                                ?>
                                <div class="megaMenuBlock leftBlocks">
                                    <div class="entry-edit">
                                        <div class="entry-edit-head">
                                            <h4><?= /* @noEscape */ __('Mega Menu Block'); ?></h4>
                                        </div>
                                        <div class="fieldset">
                                            <input class="input-text admin__control-text megamenutext megamenulabel" type="text" value="" name="mcustom_megamenu_text" />
                                            <button type="button" class="form-button megaMenuBlockAdd ui-button"><?= /* @noEscape */ __('Add to menu'); ?></button>
                                        </div>
                                    </div>
                                </div>
                                <?php
                            }
                            $category = $block->getChildHtml('catalogprint.categories');
                            if (!empty($category)) {
                                ?>
                                <div class="categoryBlock leftBlocks">
                                    <?= /* @noEscape */ $category; ?>
                                </div>
                                <?php
                            }
                            ?>
                            <div class="pageBlock leftBlocks">
                                <div class="entry-edit">
                                    <div class="entry-edit-head">
                                        <h4><?= /* @noEscape */ __('Page Selection'); ?></h4>
                                    </div>
                                    <div class="fieldset">
                                        <?= /* @noEscape */ $block->getPages(); ?>
                                        <button type="button" class="form-button pageAdd ui-button"/>
                                        <?= /* @noEscape */ __('Add to Menu'); ?></button>
                                    </div>
                                </div>
                            </div>
                            <div class="linkBlock leftBlocks">
                                <div class="entry-edit">
                                    <div class="entry-edit-head">
                                        <h4><?= /* @noEscape */ __('Add external Links'); ?></h4>
                                    </div>
                                    <div class="fieldset">
                                        <div>
                                            <h5><?= /* @noEscape */ __('Label'); ?></h5>
                                            <input class="input-text admin__control-text linktext linklabel" type="text"
                                                   value="" name="mcustom_link_text" />
                                        </div>
                                        <div>
                                            <h5><?= /* @noEscape */ __('Url'); ?></h5>
                                            <input class="input-text admin__control-text linktext linkurl validate-url"
                                                   type="url" pattern="https://.*"
                                                   value="" name="custom_link_url" />
                                        </div>
                                        <button type="button" class="form-button linkAdd ui-button"/>
                                        <?= /* @noEscape */ __('Add to menu'); ?></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-m-9">
                    <div class="admin__page-section-title">
                        <span class="title"><?= /* @noEscape */ __('Menu Items'); ?></span>
                    </div>
                    <div class="admin__page-section-content">
                        <div class="cf nestable-lists">
                            <div class="dd" id="nestable">
                                <?= /* @noEscape */ $block->getBackendMenuTree($menu->getMenuId()); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
</form>
<script type="text/x-magento-init">
{
    "#megamenu_form": {
        "Magedelight_Megamenu/js/menuitems": {}
    }
}
</script>
<style>
    .page-main-actions{
        margin: 0 0 2rem;
    }
    .page-main-actions._hidden {
        margin: 0 0 13.5rem;
    }
</style>
